builds:
  - binary: grip
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: >
      -X github.com/bmeg/grip/version.BuildDate={{.Date}}
      -X github.com/bmeg/grip/version.GitCommit={{.Commit}}
      -X github.com/bmeg/grip/version.GitBranch={{.Env.GIT_BRANCH}}
      -X github.com/bmeg/grip/version.GitUpstream={{.Env.GIT_UPSTREAM}}
      -X github.com/bmeg/grip/version.Version={{.Version}}

dist: build/release

git:
  short_hash: true

release:
  draft: true

env_files:
  github_token: .github_token

archive:
  format: tar.gz
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"

snapshot:
  name_template: "SNAPSHOT-{{.Commit}}"
