// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aql.proto

/*
Package aql is a generated protocol buffer package.

It is generated from these files:
	aql.proto

It has these top-level messages:
	GraphQuery
	QuerySet
	MatchQuerySet
	GraphStatement
	AggregationsRequest
	Aggregations
	Aggregate
	TermAggregation
	PercentileAggregation
	HistogramAggregation
	NamedAggregationResult
	AggregationResult
	WhereExpressionList
	WhereExpression
	WhereCondition
	SelectStatement
	FoldStatement
	Vertex
	Edge
	QueryResult
	ResultRow
	EditResult
	GraphElement
	Graph
	GraphID
	ElementID
	IndexID
	Timestamp
	Empty
*/
package aql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Condition int32

const (
	Condition_UNKNOWN_CONDITION Condition = 0
	Condition_EQ                Condition = 1
	Condition_NEQ               Condition = 2
	Condition_GT                Condition = 3
	Condition_GTE               Condition = 4
	Condition_LT                Condition = 5
	Condition_LTE               Condition = 6
	Condition_IN                Condition = 7
	Condition_CONTAINS          Condition = 8
)

var Condition_name = map[int32]string{
	0: "UNKNOWN_CONDITION",
	1: "EQ",
	2: "NEQ",
	3: "GT",
	4: "GTE",
	5: "LT",
	6: "LTE",
	7: "IN",
	8: "CONTAINS",
}
var Condition_value = map[string]int32{
	"UNKNOWN_CONDITION": 0,
	"EQ":                1,
	"NEQ":               2,
	"GT":                3,
	"GTE":               4,
	"LT":                5,
	"LTE":               6,
	"IN":                7,
	"CONTAINS":          8,
}

func (x Condition) String() string {
	return proto.EnumName(Condition_name, int32(x))
}
func (Condition) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ElementType int32

const (
	ElementType_UNKNOWN_TYPE ElementType = 0
	ElementType_VERTEX       ElementType = 1
	ElementType_EDGE         ElementType = 2
)

var ElementType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "VERTEX",
	2: "EDGE",
}
var ElementType_value = map[string]int32{
	"UNKNOWN_TYPE": 0,
	"VERTEX":       1,
	"EDGE":         2,
}

func (x ElementType) String() string {
	return proto.EnumName(ElementType_name, int32(x))
}
func (ElementType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GraphQuery struct {
	Graph string            `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Query []*GraphStatement `protobuf:"bytes,2,rep,name=query" json:"query,omitempty"`
}

func (m *GraphQuery) Reset()                    { *m = GraphQuery{} }
func (m *GraphQuery) String() string            { return proto.CompactTextString(m) }
func (*GraphQuery) ProtoMessage()               {}
func (*GraphQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GraphQuery) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphQuery) GetQuery() []*GraphStatement {
	if m != nil {
		return m.Query
	}
	return nil
}

type QuerySet struct {
	Query []*GraphStatement `protobuf:"bytes,1,rep,name=query" json:"query,omitempty"`
}

func (m *QuerySet) Reset()                    { *m = QuerySet{} }
func (m *QuerySet) String() string            { return proto.CompactTextString(m) }
func (*QuerySet) ProtoMessage()               {}
func (*QuerySet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QuerySet) GetQuery() []*GraphStatement {
	if m != nil {
		return m.Query
	}
	return nil
}

type MatchQuerySet struct {
	Queries []*QuerySet `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *MatchQuerySet) Reset()                    { *m = MatchQuerySet{} }
func (m *MatchQuerySet) String() string            { return proto.CompactTextString(m) }
func (*MatchQuerySet) ProtoMessage()               {}
func (*MatchQuerySet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MatchQuerySet) GetQueries() []*QuerySet {
	if m != nil {
		return m.Queries
	}
	return nil
}

type GraphStatement struct {
	// Types that are valid to be assigned to Statement:
	//	*GraphStatement_V
	//	*GraphStatement_E
	//	*GraphStatement_In
	//	*GraphStatement_Out
	//	*GraphStatement_InEdge
	//	*GraphStatement_OutEdge
	//	*GraphStatement_Both
	//	*GraphStatement_BothEdge
	//	*GraphStatement_As
	//	*GraphStatement_Select
	//	*GraphStatement_Render
	//	*GraphStatement_Limit
	//	*GraphStatement_Count
	//	*GraphStatement_Distinct
	//	*GraphStatement_Match
	//	*GraphStatement_Import
	//	*GraphStatement_Map
	//	*GraphStatement_Fold
	//	*GraphStatement_Filter
	//	*GraphStatement_Where
	//	*GraphStatement_Fields
	//	*GraphStatement_Aggregate
	Statement isGraphStatement_Statement `protobuf_oneof:"statement"`
}

func (m *GraphStatement) Reset()                    { *m = GraphStatement{} }
func (m *GraphStatement) String() string            { return proto.CompactTextString(m) }
func (*GraphStatement) ProtoMessage()               {}
func (*GraphStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isGraphStatement_Statement interface{ isGraphStatement_Statement() }

type GraphStatement_V struct {
	V *google_protobuf1.ListValue `protobuf:"bytes,1,opt,name=v,oneof"`
}
type GraphStatement_E struct {
	E *google_protobuf1.ListValue `protobuf:"bytes,2,opt,name=e,oneof"`
}
type GraphStatement_In struct {
	In *google_protobuf1.ListValue `protobuf:"bytes,10,opt,name=in,oneof"`
}
type GraphStatement_Out struct {
	Out *google_protobuf1.ListValue `protobuf:"bytes,11,opt,name=out,oneof"`
}
type GraphStatement_InEdge struct {
	InEdge *google_protobuf1.ListValue `protobuf:"bytes,12,opt,name=in_edge,json=inEdge,oneof"`
}
type GraphStatement_OutEdge struct {
	OutEdge *google_protobuf1.ListValue `protobuf:"bytes,13,opt,name=out_edge,json=outEdge,oneof"`
}
type GraphStatement_Both struct {
	Both *google_protobuf1.ListValue `protobuf:"bytes,14,opt,name=both,oneof"`
}
type GraphStatement_BothEdge struct {
	BothEdge *google_protobuf1.ListValue `protobuf:"bytes,15,opt,name=both_edge,json=bothEdge,oneof"`
}
type GraphStatement_As struct {
	As string `protobuf:"bytes,20,opt,name=as,oneof"`
}
type GraphStatement_Select struct {
	Select *SelectStatement `protobuf:"bytes,21,opt,name=select,oneof"`
}
type GraphStatement_Render struct {
	Render *google_protobuf1.Value `protobuf:"bytes,23,opt,name=render,oneof"`
}
type GraphStatement_Limit struct {
	Limit int64 `protobuf:"varint,25,opt,name=limit,oneof"`
}
type GraphStatement_Count struct {
	Count string `protobuf:"bytes,26,opt,name=count,oneof"`
}
type GraphStatement_Distinct struct {
	Distinct *google_protobuf1.ListValue `protobuf:"bytes,31,opt,name=distinct,oneof"`
}
type GraphStatement_Match struct {
	Match *MatchQuerySet `protobuf:"bytes,40,opt,name=match,oneof"`
}
type GraphStatement_Import struct {
	Import string `protobuf:"bytes,50,opt,name=import,oneof"`
}
type GraphStatement_Map struct {
	Map string `protobuf:"bytes,51,opt,name=map,oneof"`
}
type GraphStatement_Fold struct {
	Fold *FoldStatement `protobuf:"bytes,52,opt,name=fold,oneof"`
}
type GraphStatement_Filter struct {
	Filter string `protobuf:"bytes,54,opt,name=filter,oneof"`
}
type GraphStatement_Where struct {
	Where *WhereExpression `protobuf:"bytes,57,opt,name=where,oneof"`
}
type GraphStatement_Fields struct {
	Fields *google_protobuf1.ListValue `protobuf:"bytes,58,opt,name=fields,oneof"`
}
type GraphStatement_Aggregate struct {
	Aggregate *Aggregations `protobuf:"bytes,59,opt,name=aggregate,oneof"`
}

func (*GraphStatement_V) isGraphStatement_Statement()         {}
func (*GraphStatement_E) isGraphStatement_Statement()         {}
func (*GraphStatement_In) isGraphStatement_Statement()        {}
func (*GraphStatement_Out) isGraphStatement_Statement()       {}
func (*GraphStatement_InEdge) isGraphStatement_Statement()    {}
func (*GraphStatement_OutEdge) isGraphStatement_Statement()   {}
func (*GraphStatement_Both) isGraphStatement_Statement()      {}
func (*GraphStatement_BothEdge) isGraphStatement_Statement()  {}
func (*GraphStatement_As) isGraphStatement_Statement()        {}
func (*GraphStatement_Select) isGraphStatement_Statement()    {}
func (*GraphStatement_Render) isGraphStatement_Statement()    {}
func (*GraphStatement_Limit) isGraphStatement_Statement()     {}
func (*GraphStatement_Count) isGraphStatement_Statement()     {}
func (*GraphStatement_Distinct) isGraphStatement_Statement()  {}
func (*GraphStatement_Match) isGraphStatement_Statement()     {}
func (*GraphStatement_Import) isGraphStatement_Statement()    {}
func (*GraphStatement_Map) isGraphStatement_Statement()       {}
func (*GraphStatement_Fold) isGraphStatement_Statement()      {}
func (*GraphStatement_Filter) isGraphStatement_Statement()    {}
func (*GraphStatement_Where) isGraphStatement_Statement()     {}
func (*GraphStatement_Fields) isGraphStatement_Statement()    {}
func (*GraphStatement_Aggregate) isGraphStatement_Statement() {}

func (m *GraphStatement) GetStatement() isGraphStatement_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *GraphStatement) GetV() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_V); ok {
		return x.V
	}
	return nil
}

func (m *GraphStatement) GetE() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_E); ok {
		return x.E
	}
	return nil
}

func (m *GraphStatement) GetIn() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_In); ok {
		return x.In
	}
	return nil
}

func (m *GraphStatement) GetOut() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Out); ok {
		return x.Out
	}
	return nil
}

func (m *GraphStatement) GetInEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_InEdge); ok {
		return x.InEdge
	}
	return nil
}

func (m *GraphStatement) GetOutEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_OutEdge); ok {
		return x.OutEdge
	}
	return nil
}

func (m *GraphStatement) GetBoth() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Both); ok {
		return x.Both
	}
	return nil
}

func (m *GraphStatement) GetBothEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_BothEdge); ok {
		return x.BothEdge
	}
	return nil
}

func (m *GraphStatement) GetAs() string {
	if x, ok := m.GetStatement().(*GraphStatement_As); ok {
		return x.As
	}
	return ""
}

func (m *GraphStatement) GetSelect() *SelectStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Select); ok {
		return x.Select
	}
	return nil
}

func (m *GraphStatement) GetRender() *google_protobuf1.Value {
	if x, ok := m.GetStatement().(*GraphStatement_Render); ok {
		return x.Render
	}
	return nil
}

func (m *GraphStatement) GetLimit() int64 {
	if x, ok := m.GetStatement().(*GraphStatement_Limit); ok {
		return x.Limit
	}
	return 0
}

func (m *GraphStatement) GetCount() string {
	if x, ok := m.GetStatement().(*GraphStatement_Count); ok {
		return x.Count
	}
	return ""
}

func (m *GraphStatement) GetDistinct() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Distinct); ok {
		return x.Distinct
	}
	return nil
}

func (m *GraphStatement) GetMatch() *MatchQuerySet {
	if x, ok := m.GetStatement().(*GraphStatement_Match); ok {
		return x.Match
	}
	return nil
}

func (m *GraphStatement) GetImport() string {
	if x, ok := m.GetStatement().(*GraphStatement_Import); ok {
		return x.Import
	}
	return ""
}

func (m *GraphStatement) GetMap() string {
	if x, ok := m.GetStatement().(*GraphStatement_Map); ok {
		return x.Map
	}
	return ""
}

func (m *GraphStatement) GetFold() *FoldStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Fold); ok {
		return x.Fold
	}
	return nil
}

func (m *GraphStatement) GetFilter() string {
	if x, ok := m.GetStatement().(*GraphStatement_Filter); ok {
		return x.Filter
	}
	return ""
}

func (m *GraphStatement) GetWhere() *WhereExpression {
	if x, ok := m.GetStatement().(*GraphStatement_Where); ok {
		return x.Where
	}
	return nil
}

func (m *GraphStatement) GetFields() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Fields); ok {
		return x.Fields
	}
	return nil
}

func (m *GraphStatement) GetAggregate() *Aggregations {
	if x, ok := m.GetStatement().(*GraphStatement_Aggregate); ok {
		return x.Aggregate
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GraphStatement) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GraphStatement_OneofMarshaler, _GraphStatement_OneofUnmarshaler, _GraphStatement_OneofSizer, []interface{}{
		(*GraphStatement_V)(nil),
		(*GraphStatement_E)(nil),
		(*GraphStatement_In)(nil),
		(*GraphStatement_Out)(nil),
		(*GraphStatement_InEdge)(nil),
		(*GraphStatement_OutEdge)(nil),
		(*GraphStatement_Both)(nil),
		(*GraphStatement_BothEdge)(nil),
		(*GraphStatement_As)(nil),
		(*GraphStatement_Select)(nil),
		(*GraphStatement_Render)(nil),
		(*GraphStatement_Limit)(nil),
		(*GraphStatement_Count)(nil),
		(*GraphStatement_Distinct)(nil),
		(*GraphStatement_Match)(nil),
		(*GraphStatement_Import)(nil),
		(*GraphStatement_Map)(nil),
		(*GraphStatement_Fold)(nil),
		(*GraphStatement_Filter)(nil),
		(*GraphStatement_Where)(nil),
		(*GraphStatement_Fields)(nil),
		(*GraphStatement_Aggregate)(nil),
	}
}

func _GraphStatement_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.V); err != nil {
			return err
		}
	case *GraphStatement_E:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.E); err != nil {
			return err
		}
	case *GraphStatement_In:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.In); err != nil {
			return err
		}
	case *GraphStatement_Out:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Out); err != nil {
			return err
		}
	case *GraphStatement_InEdge:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InEdge); err != nil {
			return err
		}
	case *GraphStatement_OutEdge:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OutEdge); err != nil {
			return err
		}
	case *GraphStatement_Both:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Both); err != nil {
			return err
		}
	case *GraphStatement_BothEdge:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BothEdge); err != nil {
			return err
		}
	case *GraphStatement_As:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.As)
	case *GraphStatement_Select:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Select); err != nil {
			return err
		}
	case *GraphStatement_Render:
		b.EncodeVarint(23<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Render); err != nil {
			return err
		}
	case *GraphStatement_Limit:
		b.EncodeVarint(25<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		b.EncodeVarint(26<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Count)
	case *GraphStatement_Distinct:
		b.EncodeVarint(31<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Distinct); err != nil {
			return err
		}
	case *GraphStatement_Match:
		b.EncodeVarint(40<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Match); err != nil {
			return err
		}
	case *GraphStatement_Import:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Import)
	case *GraphStatement_Map:
		b.EncodeVarint(51<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Map)
	case *GraphStatement_Fold:
		b.EncodeVarint(52<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fold); err != nil {
			return err
		}
	case *GraphStatement_Filter:
		b.EncodeVarint(54<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Filter)
	case *GraphStatement_Where:
		b.EncodeVarint(57<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Where); err != nil {
			return err
		}
	case *GraphStatement_Fields:
		b.EncodeVarint(58<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fields); err != nil {
			return err
		}
	case *GraphStatement_Aggregate:
		b.EncodeVarint(59<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aggregate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GraphStatement.Statement has unexpected type %T", x)
	}
	return nil
}

func _GraphStatement_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GraphStatement)
	switch tag {
	case 1: // statement.v
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_V{msg}
		return true, err
	case 2: // statement.e
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_E{msg}
		return true, err
	case 10: // statement.in
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_In{msg}
		return true, err
	case 11: // statement.out
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Out{msg}
		return true, err
	case 12: // statement.in_edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_InEdge{msg}
		return true, err
	case 13: // statement.out_edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_OutEdge{msg}
		return true, err
	case 14: // statement.both
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Both{msg}
		return true, err
	case 15: // statement.both_edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_BothEdge{msg}
		return true, err
	case 20: // statement.as
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_As{x}
		return true, err
	case 21: // statement.select
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SelectStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Select{msg}
		return true, err
	case 23: // statement.render
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Value)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Render{msg}
		return true, err
	case 25: // statement.limit
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Statement = &GraphStatement_Limit{int64(x)}
		return true, err
	case 26: // statement.count
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Count{x}
		return true, err
	case 31: // statement.distinct
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Distinct{msg}
		return true, err
	case 40: // statement.match
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchQuerySet)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Match{msg}
		return true, err
	case 50: // statement.import
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Import{x}
		return true, err
	case 51: // statement.map
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Map{x}
		return true, err
	case 52: // statement.fold
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FoldStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Fold{msg}
		return true, err
	case 54: // statement.filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Filter{x}
		return true, err
	case 57: // statement.where
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhereExpression)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Where{msg}
		return true, err
	case 58: // statement.fields
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Fields{msg}
		return true, err
	case 59: // statement.aggregate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Aggregations)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Aggregate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GraphStatement_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		s := proto.Size(x.V)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_E:
		s := proto.Size(x.E)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_In:
		s := proto.Size(x.In)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Out:
		s := proto.Size(x.Out)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_InEdge:
		s := proto.Size(x.InEdge)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_OutEdge:
		s := proto.Size(x.OutEdge)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Both:
		s := proto.Size(x.Both)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_BothEdge:
		s := proto.Size(x.BothEdge)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_As:
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.As)))
		n += len(x.As)
	case *GraphStatement_Select:
		s := proto.Size(x.Select)
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Render:
		s := proto.Size(x.Render)
		n += proto.SizeVarint(23<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Limit:
		n += proto.SizeVarint(25<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		n += proto.SizeVarint(26<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Count)))
		n += len(x.Count)
	case *GraphStatement_Distinct:
		s := proto.Size(x.Distinct)
		n += proto.SizeVarint(31<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Match:
		s := proto.Size(x.Match)
		n += proto.SizeVarint(40<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Import:
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Import)))
		n += len(x.Import)
	case *GraphStatement_Map:
		n += proto.SizeVarint(51<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Map)))
		n += len(x.Map)
	case *GraphStatement_Fold:
		s := proto.Size(x.Fold)
		n += proto.SizeVarint(52<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Filter:
		n += proto.SizeVarint(54<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Filter)))
		n += len(x.Filter)
	case *GraphStatement_Where:
		s := proto.Size(x.Where)
		n += proto.SizeVarint(57<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Fields:
		s := proto.Size(x.Fields)
		n += proto.SizeVarint(58<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Aggregate:
		s := proto.Size(x.Aggregate)
		n += proto.SizeVarint(59<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AggregationsRequest struct {
	Graph        string       `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Aggregations []*Aggregate `protobuf:"bytes,2,rep,name=aggregations" json:"aggregations,omitempty"`
}

func (m *AggregationsRequest) Reset()                    { *m = AggregationsRequest{} }
func (m *AggregationsRequest) String() string            { return proto.CompactTextString(m) }
func (*AggregationsRequest) ProtoMessage()               {}
func (*AggregationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AggregationsRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *AggregationsRequest) GetAggregations() []*Aggregate {
	if m != nil {
		return m.Aggregations
	}
	return nil
}

type Aggregations struct {
	Aggregations []*Aggregate `protobuf:"bytes,1,rep,name=aggregations" json:"aggregations,omitempty"`
}

func (m *Aggregations) Reset()                    { *m = Aggregations{} }
func (m *Aggregations) String() string            { return proto.CompactTextString(m) }
func (*Aggregations) ProtoMessage()               {}
func (*Aggregations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Aggregations) GetAggregations() []*Aggregate {
	if m != nil {
		return m.Aggregations
	}
	return nil
}

type Aggregate struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Aggregation:
	//	*Aggregate_Term
	//	*Aggregate_Percentile
	//	*Aggregate_Histogram
	Aggregation isAggregate_Aggregation `protobuf_oneof:"aggregation"`
}

func (m *Aggregate) Reset()                    { *m = Aggregate{} }
func (m *Aggregate) String() string            { return proto.CompactTextString(m) }
func (*Aggregate) ProtoMessage()               {}
func (*Aggregate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isAggregate_Aggregation interface{ isAggregate_Aggregation() }

type Aggregate_Term struct {
	Term *TermAggregation `protobuf:"bytes,2,opt,name=term,oneof"`
}
type Aggregate_Percentile struct {
	Percentile *PercentileAggregation `protobuf:"bytes,3,opt,name=percentile,oneof"`
}
type Aggregate_Histogram struct {
	Histogram *HistogramAggregation `protobuf:"bytes,4,opt,name=histogram,oneof"`
}

func (*Aggregate_Term) isAggregate_Aggregation()       {}
func (*Aggregate_Percentile) isAggregate_Aggregation() {}
func (*Aggregate_Histogram) isAggregate_Aggregation()  {}

func (m *Aggregate) GetAggregation() isAggregate_Aggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

func (m *Aggregate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Aggregate) GetTerm() *TermAggregation {
	if x, ok := m.GetAggregation().(*Aggregate_Term); ok {
		return x.Term
	}
	return nil
}

func (m *Aggregate) GetPercentile() *PercentileAggregation {
	if x, ok := m.GetAggregation().(*Aggregate_Percentile); ok {
		return x.Percentile
	}
	return nil
}

func (m *Aggregate) GetHistogram() *HistogramAggregation {
	if x, ok := m.GetAggregation().(*Aggregate_Histogram); ok {
		return x.Histogram
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Aggregate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Aggregate_OneofMarshaler, _Aggregate_OneofUnmarshaler, _Aggregate_OneofSizer, []interface{}{
		(*Aggregate_Term)(nil),
		(*Aggregate_Percentile)(nil),
		(*Aggregate_Histogram)(nil),
	}
}

func _Aggregate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Aggregate)
	// aggregation
	switch x := m.Aggregation.(type) {
	case *Aggregate_Term:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Term); err != nil {
			return err
		}
	case *Aggregate_Percentile:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Percentile); err != nil {
			return err
		}
	case *Aggregate_Histogram:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Histogram); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Aggregate.Aggregation has unexpected type %T", x)
	}
	return nil
}

func _Aggregate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Aggregate)
	switch tag {
	case 2: // aggregation.term
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TermAggregation)
		err := b.DecodeMessage(msg)
		m.Aggregation = &Aggregate_Term{msg}
		return true, err
	case 3: // aggregation.percentile
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PercentileAggregation)
		err := b.DecodeMessage(msg)
		m.Aggregation = &Aggregate_Percentile{msg}
		return true, err
	case 4: // aggregation.histogram
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HistogramAggregation)
		err := b.DecodeMessage(msg)
		m.Aggregation = &Aggregate_Histogram{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Aggregate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Aggregate)
	// aggregation
	switch x := m.Aggregation.(type) {
	case *Aggregate_Term:
		s := proto.Size(x.Term)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Aggregate_Percentile:
		s := proto.Size(x.Percentile)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Aggregate_Histogram:
		s := proto.Size(x.Histogram)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TermAggregation struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	Size  uint64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *TermAggregation) Reset()                    { *m = TermAggregation{} }
func (m *TermAggregation) String() string            { return proto.CompactTextString(m) }
func (*TermAggregation) ProtoMessage()               {}
func (*TermAggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TermAggregation) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *TermAggregation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *TermAggregation) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PercentileAggregation struct {
	Label    string    `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Field    string    `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	Percents []float64 `protobuf:"fixed64,3,rep,packed,name=percents" json:"percents,omitempty"`
}

func (m *PercentileAggregation) Reset()                    { *m = PercentileAggregation{} }
func (m *PercentileAggregation) String() string            { return proto.CompactTextString(m) }
func (*PercentileAggregation) ProtoMessage()               {}
func (*PercentileAggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PercentileAggregation) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PercentileAggregation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *PercentileAggregation) GetPercents() []float64 {
	if m != nil {
		return m.Percents
	}
	return nil
}

type HistogramAggregation struct {
	Label    string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Field    string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	Interval uint64 `protobuf:"varint,3,opt,name=interval" json:"interval,omitempty"`
}

func (m *HistogramAggregation) Reset()                    { *m = HistogramAggregation{} }
func (m *HistogramAggregation) String() string            { return proto.CompactTextString(m) }
func (*HistogramAggregation) ProtoMessage()               {}
func (*HistogramAggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HistogramAggregation) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *HistogramAggregation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *HistogramAggregation) GetInterval() uint64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type NamedAggregationResult struct {
	Name    string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Buckets []*AggregationResult `protobuf:"bytes,2,rep,name=buckets" json:"buckets,omitempty"`
}

func (m *NamedAggregationResult) Reset()                    { *m = NamedAggregationResult{} }
func (m *NamedAggregationResult) String() string            { return proto.CompactTextString(m) }
func (*NamedAggregationResult) ProtoMessage()               {}
func (*NamedAggregationResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *NamedAggregationResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedAggregationResult) GetBuckets() []*AggregationResult {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type AggregationResult struct {
	Key   *google_protobuf1.Value `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value float64                 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *AggregationResult) Reset()                    { *m = AggregationResult{} }
func (m *AggregationResult) String() string            { return proto.CompactTextString(m) }
func (*AggregationResult) ProtoMessage()               {}
func (*AggregationResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AggregationResult) GetKey() *google_protobuf1.Value {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AggregationResult) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type WhereExpressionList struct {
	Expressions []*WhereExpression `protobuf:"bytes,1,rep,name=expressions" json:"expressions,omitempty"`
}

func (m *WhereExpressionList) Reset()                    { *m = WhereExpressionList{} }
func (m *WhereExpressionList) String() string            { return proto.CompactTextString(m) }
func (*WhereExpressionList) ProtoMessage()               {}
func (*WhereExpressionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *WhereExpressionList) GetExpressions() []*WhereExpression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type WhereExpression struct {
	// Types that are valid to be assigned to Expression:
	//	*WhereExpression_And
	//	*WhereExpression_Or
	//	*WhereExpression_Not
	//	*WhereExpression_Condition
	Expression isWhereExpression_Expression `protobuf_oneof:"expression"`
}

func (m *WhereExpression) Reset()                    { *m = WhereExpression{} }
func (m *WhereExpression) String() string            { return proto.CompactTextString(m) }
func (*WhereExpression) ProtoMessage()               {}
func (*WhereExpression) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isWhereExpression_Expression interface{ isWhereExpression_Expression() }

type WhereExpression_And struct {
	And *WhereExpressionList `protobuf:"bytes,1,opt,name=and,oneof"`
}
type WhereExpression_Or struct {
	Or *WhereExpressionList `protobuf:"bytes,2,opt,name=or,oneof"`
}
type WhereExpression_Not struct {
	Not *WhereExpression `protobuf:"bytes,3,opt,name=not,oneof"`
}
type WhereExpression_Condition struct {
	Condition *WhereCondition `protobuf:"bytes,4,opt,name=condition,oneof"`
}

func (*WhereExpression_And) isWhereExpression_Expression()       {}
func (*WhereExpression_Or) isWhereExpression_Expression()        {}
func (*WhereExpression_Not) isWhereExpression_Expression()       {}
func (*WhereExpression_Condition) isWhereExpression_Expression() {}

func (m *WhereExpression) GetExpression() isWhereExpression_Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

func (m *WhereExpression) GetAnd() *WhereExpressionList {
	if x, ok := m.GetExpression().(*WhereExpression_And); ok {
		return x.And
	}
	return nil
}

func (m *WhereExpression) GetOr() *WhereExpressionList {
	if x, ok := m.GetExpression().(*WhereExpression_Or); ok {
		return x.Or
	}
	return nil
}

func (m *WhereExpression) GetNot() *WhereExpression {
	if x, ok := m.GetExpression().(*WhereExpression_Not); ok {
		return x.Not
	}
	return nil
}

func (m *WhereExpression) GetCondition() *WhereCondition {
	if x, ok := m.GetExpression().(*WhereExpression_Condition); ok {
		return x.Condition
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WhereExpression) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WhereExpression_OneofMarshaler, _WhereExpression_OneofUnmarshaler, _WhereExpression_OneofSizer, []interface{}{
		(*WhereExpression_And)(nil),
		(*WhereExpression_Or)(nil),
		(*WhereExpression_Not)(nil),
		(*WhereExpression_Condition)(nil),
	}
}

func _WhereExpression_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WhereExpression)
	// expression
	switch x := m.Expression.(type) {
	case *WhereExpression_And:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.And); err != nil {
			return err
		}
	case *WhereExpression_Or:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Or); err != nil {
			return err
		}
	case *WhereExpression_Not:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Not); err != nil {
			return err
		}
	case *WhereExpression_Condition:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Condition); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WhereExpression.Expression has unexpected type %T", x)
	}
	return nil
}

func _WhereExpression_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WhereExpression)
	switch tag {
	case 1: // expression.and
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhereExpressionList)
		err := b.DecodeMessage(msg)
		m.Expression = &WhereExpression_And{msg}
		return true, err
	case 2: // expression.or
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhereExpressionList)
		err := b.DecodeMessage(msg)
		m.Expression = &WhereExpression_Or{msg}
		return true, err
	case 3: // expression.not
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhereExpression)
		err := b.DecodeMessage(msg)
		m.Expression = &WhereExpression_Not{msg}
		return true, err
	case 4: // expression.condition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhereCondition)
		err := b.DecodeMessage(msg)
		m.Expression = &WhereExpression_Condition{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WhereExpression_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WhereExpression)
	// expression
	switch x := m.Expression.(type) {
	case *WhereExpression_And:
		s := proto.Size(x.And)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WhereExpression_Or:
		s := proto.Size(x.Or)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WhereExpression_Not:
		s := proto.Size(x.Not)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WhereExpression_Condition:
		s := proto.Size(x.Condition)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type WhereCondition struct {
	Key       string                  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value     *google_protobuf1.Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Condition Condition               `protobuf:"varint,3,opt,name=condition,enum=aql.Condition" json:"condition,omitempty"`
}

func (m *WhereCondition) Reset()                    { *m = WhereCondition{} }
func (m *WhereCondition) String() string            { return proto.CompactTextString(m) }
func (*WhereCondition) ProtoMessage()               {}
func (*WhereCondition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *WhereCondition) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WhereCondition) GetValue() *google_protobuf1.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WhereCondition) GetCondition() Condition {
	if m != nil {
		return m.Condition
	}
	return Condition_UNKNOWN_CONDITION
}

type SelectStatement struct {
	Labels []string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
}

func (m *SelectStatement) Reset()                    { *m = SelectStatement{} }
func (m *SelectStatement) String() string            { return proto.CompactTextString(m) }
func (*SelectStatement) ProtoMessage()               {}
func (*SelectStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SelectStatement) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type FoldStatement struct {
	Source string                  `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Init   *google_protobuf1.Value `protobuf:"bytes,2,opt,name=init" json:"init,omitempty"`
}

func (m *FoldStatement) Reset()                    { *m = FoldStatement{} }
func (m *FoldStatement) String() string            { return proto.CompactTextString(m) }
func (*FoldStatement) ProtoMessage()               {}
func (*FoldStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *FoldStatement) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *FoldStatement) GetInit() *google_protobuf1.Value {
	if m != nil {
		return m.Init
	}
	return nil
}

type Vertex struct {
	Gid   string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Data  *google_protobuf1.Struct `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Vertex) Reset()                    { *m = Vertex{} }
func (m *Vertex) String() string            { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()               {}
func (*Vertex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Vertex) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Vertex) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Vertex) GetData() *google_protobuf1.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type Edge struct {
	Gid   string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	From  string                   `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To    string                   `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Data  *google_protobuf1.Struct `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Edge) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Edge) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Edge) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Edge) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Edge) GetData() *google_protobuf1.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*QueryResult_Vertex
	//	*QueryResult_Edge
	//	*QueryResult_Data
	Result isQueryResult_Result `protobuf_oneof:"result"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type isQueryResult_Result interface{ isQueryResult_Result() }

type QueryResult_Vertex struct {
	Vertex *Vertex `protobuf:"bytes,1,opt,name=vertex,oneof"`
}
type QueryResult_Edge struct {
	Edge *Edge `protobuf:"bytes,2,opt,name=edge,oneof"`
}
type QueryResult_Data struct {
	Data *google_protobuf1.Value `protobuf:"bytes,4,opt,name=data,oneof"`
}

func (*QueryResult_Vertex) isQueryResult_Result() {}
func (*QueryResult_Edge) isQueryResult_Result()   {}
func (*QueryResult_Data) isQueryResult_Result()   {}

func (m *QueryResult) GetResult() isQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *QueryResult) GetVertex() *Vertex {
	if x, ok := m.GetResult().(*QueryResult_Vertex); ok {
		return x.Vertex
	}
	return nil
}

func (m *QueryResult) GetEdge() *Edge {
	if x, ok := m.GetResult().(*QueryResult_Edge); ok {
		return x.Edge
	}
	return nil
}

func (m *QueryResult) GetData() *google_protobuf1.Value {
	if x, ok := m.GetResult().(*QueryResult_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueryResult_OneofMarshaler, _QueryResult_OneofUnmarshaler, _QueryResult_OneofSizer, []interface{}{
		(*QueryResult_Vertex)(nil),
		(*QueryResult_Edge)(nil),
		(*QueryResult_Data)(nil),
	}
}

func _QueryResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Vertex:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vertex); err != nil {
			return err
		}
	case *QueryResult_Edge:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Edge); err != nil {
			return err
		}
	case *QueryResult_Data:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _QueryResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueryResult)
	switch tag {
	case 1: // result.vertex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Vertex)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Vertex{msg}
		return true, err
	case 2: // result.edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Edge)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Edge{msg}
		return true, err
	case 4: // result.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Value)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Data{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueryResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Vertex:
		s := proto.Size(x.Vertex)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Edge:
		s := proto.Size(x.Edge)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Data:
		s := proto.Size(x.Data)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResultRow struct {
	Value *QueryResult   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Row   []*QueryResult `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *ResultRow) Reset()                    { *m = ResultRow{} }
func (m *ResultRow) String() string            { return proto.CompactTextString(m) }
func (*ResultRow) ProtoMessage()               {}
func (*ResultRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ResultRow) GetValue() *QueryResult {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResultRow) GetRow() []*QueryResult {
	if m != nil {
		return m.Row
	}
	return nil
}

type EditResult struct {
	// Types that are valid to be assigned to Result:
	//	*EditResult_Error
	//	*EditResult_Id
	Result isEditResult_Result `protobuf_oneof:"result"`
}

func (m *EditResult) Reset()                    { *m = EditResult{} }
func (m *EditResult) String() string            { return proto.CompactTextString(m) }
func (*EditResult) ProtoMessage()               {}
func (*EditResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type isEditResult_Result interface{ isEditResult_Result() }

type EditResult_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,oneof"`
}
type EditResult_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,oneof"`
}

func (*EditResult_Error) isEditResult_Result() {}
func (*EditResult_Id) isEditResult_Result()    {}

func (m *EditResult) GetResult() isEditResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EditResult) GetError() string {
	if x, ok := m.GetResult().(*EditResult_Error); ok {
		return x.Error
	}
	return ""
}

func (m *EditResult) GetId() string {
	if x, ok := m.GetResult().(*EditResult_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EditResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EditResult_OneofMarshaler, _EditResult_OneofUnmarshaler, _EditResult_OneofSizer, []interface{}{
		(*EditResult_Error)(nil),
		(*EditResult_Id)(nil),
	}
}

func _EditResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case *EditResult_Id:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case nil:
	default:
		return fmt.Errorf("EditResult.Result has unexpected type %T", x)
	}
	return nil
}

func _EditResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EditResult)
	switch tag {
	case 1: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Error{x}
		return true, err
	case 2: // result.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Id{x}
		return true, err
	default:
		return false, nil
	}
}

func _EditResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case *EditResult_Id:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GraphElement struct {
	Graph  string  `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Vertex *Vertex `protobuf:"bytes,2,opt,name=vertex" json:"vertex,omitempty"`
	Edge   *Edge   `protobuf:"bytes,3,opt,name=edge" json:"edge,omitempty"`
}

func (m *GraphElement) Reset()                    { *m = GraphElement{} }
func (m *GraphElement) String() string            { return proto.CompactTextString(m) }
func (*GraphElement) ProtoMessage()               {}
func (*GraphElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GraphElement) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphElement) GetVertex() *Vertex {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *GraphElement) GetEdge() *Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

type Graph struct {
	Graph    string    `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Edges    []*Edge   `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	Vertices []*Vertex `protobuf:"bytes,3,rep,name=vertices" json:"vertices,omitempty"`
}

func (m *Graph) Reset()                    { *m = Graph{} }
func (m *Graph) String() string            { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()               {}
func (*Graph) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Graph) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *Graph) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *Graph) GetVertices() []*Vertex {
	if m != nil {
		return m.Vertices
	}
	return nil
}

type GraphID struct {
	Graph string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
}

func (m *GraphID) Reset()                    { *m = GraphID{} }
func (m *GraphID) String() string            { return proto.CompactTextString(m) }
func (*GraphID) ProtoMessage()               {}
func (*GraphID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GraphID) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

type ElementID struct {
	Graph string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ElementID) Reset()                    { *m = ElementID{} }
func (m *ElementID) String() string            { return proto.CompactTextString(m) }
func (*ElementID) ProtoMessage()               {}
func (*ElementID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ElementID) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *ElementID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type IndexID struct {
	Graph string      `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Label string      `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Field string      `protobuf:"bytes,3,opt,name=field" json:"field,omitempty"`
	Type  ElementType `protobuf:"varint,4,opt,name=type,enum=aql.ElementType" json:"type,omitempty"`
}

func (m *IndexID) Reset()                    { *m = IndexID{} }
func (m *IndexID) String() string            { return proto.CompactTextString(m) }
func (*IndexID) ProtoMessage()               {}
func (*IndexID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *IndexID) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *IndexID) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *IndexID) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *IndexID) GetType() ElementType {
	if m != nil {
		return m.Type
	}
	return ElementType_UNKNOWN_TYPE
}

type Timestamp struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Timestamp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func init() {
	proto.RegisterType((*GraphQuery)(nil), "aql.GraphQuery")
	proto.RegisterType((*QuerySet)(nil), "aql.QuerySet")
	proto.RegisterType((*MatchQuerySet)(nil), "aql.MatchQuerySet")
	proto.RegisterType((*GraphStatement)(nil), "aql.GraphStatement")
	proto.RegisterType((*AggregationsRequest)(nil), "aql.AggregationsRequest")
	proto.RegisterType((*Aggregations)(nil), "aql.Aggregations")
	proto.RegisterType((*Aggregate)(nil), "aql.Aggregate")
	proto.RegisterType((*TermAggregation)(nil), "aql.TermAggregation")
	proto.RegisterType((*PercentileAggregation)(nil), "aql.PercentileAggregation")
	proto.RegisterType((*HistogramAggregation)(nil), "aql.HistogramAggregation")
	proto.RegisterType((*NamedAggregationResult)(nil), "aql.NamedAggregationResult")
	proto.RegisterType((*AggregationResult)(nil), "aql.AggregationResult")
	proto.RegisterType((*WhereExpressionList)(nil), "aql.WhereExpressionList")
	proto.RegisterType((*WhereExpression)(nil), "aql.WhereExpression")
	proto.RegisterType((*WhereCondition)(nil), "aql.WhereCondition")
	proto.RegisterType((*SelectStatement)(nil), "aql.SelectStatement")
	proto.RegisterType((*FoldStatement)(nil), "aql.FoldStatement")
	proto.RegisterType((*Vertex)(nil), "aql.Vertex")
	proto.RegisterType((*Edge)(nil), "aql.Edge")
	proto.RegisterType((*QueryResult)(nil), "aql.QueryResult")
	proto.RegisterType((*ResultRow)(nil), "aql.ResultRow")
	proto.RegisterType((*EditResult)(nil), "aql.EditResult")
	proto.RegisterType((*GraphElement)(nil), "aql.GraphElement")
	proto.RegisterType((*Graph)(nil), "aql.Graph")
	proto.RegisterType((*GraphID)(nil), "aql.GraphID")
	proto.RegisterType((*ElementID)(nil), "aql.ElementID")
	proto.RegisterType((*IndexID)(nil), "aql.IndexID")
	proto.RegisterType((*Timestamp)(nil), "aql.Timestamp")
	proto.RegisterType((*Empty)(nil), "aql.Empty")
	proto.RegisterEnum("aql.Condition", Condition_name, Condition_value)
	proto.RegisterEnum("aql.ElementType", ElementType_name, ElementType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Query service

type QueryClient interface {
	Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error)
	Aggregate(ctx context.Context, in *AggregationsRequest, opts ...grpc.CallOption) (Query_AggregateClient, error)
	GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error)
	GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error)
	GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error)
	GetIndexList(ctx context.Context, in *GraphID, opts ...grpc.CallOption) (Query_GetIndexListClient, error)
	GetTimestamp(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Timestamp, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[0], c.cc, "/aql.Query/Traversal", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryTraversalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_TraversalClient interface {
	Recv() (*ResultRow, error)
	grpc.ClientStream
}

type queryTraversalClient struct {
	grpc.ClientStream
}

func (x *queryTraversalClient) Recv() (*ResultRow, error) {
	m := new(ResultRow)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) Aggregate(ctx context.Context, in *AggregationsRequest, opts ...grpc.CallOption) (Query_AggregateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[1], c.cc, "/aql.Query/Aggregate", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryAggregateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_AggregateClient interface {
	Recv() (*NamedAggregationResult, error)
	grpc.ClientStream
}

type queryAggregateClient struct {
	grpc.ClientStream
}

func (x *queryAggregateClient) Recv() (*NamedAggregationResult, error) {
	m := new(NamedAggregationResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error) {
	out := new(Vertex)
	err := grpc.Invoke(ctx, "/aql.Query/GetVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error) {
	out := new(Edge)
	err := grpc.Invoke(ctx, "/aql.Query/GetEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[2], c.cc, "/aql.Query/GetGraphs", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryGetGraphsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_GetGraphsClient interface {
	Recv() (*ElementID, error)
	grpc.ClientStream
}

type queryGetGraphsClient struct {
	grpc.ClientStream
}

func (x *queryGetGraphsClient) Recv() (*ElementID, error) {
	m := new(ElementID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetIndexList(ctx context.Context, in *GraphID, opts ...grpc.CallOption) (Query_GetIndexListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[3], c.cc, "/aql.Query/GetIndexList", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryGetIndexListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_GetIndexListClient interface {
	Recv() (*IndexID, error)
	grpc.ClientStream
}

type queryGetIndexListClient struct {
	grpc.ClientStream
}

func (x *queryGetIndexListClient) Recv() (*IndexID, error) {
	m := new(IndexID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetTimestamp(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Timestamp, error) {
	out := new(Timestamp)
	err := grpc.Invoke(ctx, "/aql.Query/GetTimestamp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Query service

type QueryServer interface {
	Traversal(*GraphQuery, Query_TraversalServer) error
	Aggregate(*AggregationsRequest, Query_AggregateServer) error
	GetVertex(context.Context, *ElementID) (*Vertex, error)
	GetEdge(context.Context, *ElementID) (*Edge, error)
	GetGraphs(*Empty, Query_GetGraphsServer) error
	GetIndexList(*GraphID, Query_GetIndexListServer) error
	GetTimestamp(context.Context, *ElementID) (*Timestamp, error)
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Traversal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GraphQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).Traversal(m, &queryTraversalServer{stream})
}

type Query_TraversalServer interface {
	Send(*ResultRow) error
	grpc.ServerStream
}

type queryTraversalServer struct {
	grpc.ServerStream
}

func (x *queryTraversalServer) Send(m *ResultRow) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_Aggregate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AggregationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).Aggregate(m, &queryAggregateServer{stream})
}

type Query_AggregateServer interface {
	Send(*NamedAggregationResult) error
	grpc.ServerStream
}

type queryAggregateServer struct {
	grpc.ServerStream
}

func (x *queryAggregateServer) Send(m *NamedAggregationResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGraphs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).GetGraphs(m, &queryGetGraphsServer{stream})
}

type Query_GetGraphsServer interface {
	Send(*ElementID) error
	grpc.ServerStream
}

type queryGetGraphsServer struct {
	grpc.ServerStream
}

func (x *queryGetGraphsServer) Send(m *ElementID) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetIndexList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GraphID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).GetIndexList(m, &queryGetIndexListServer{stream})
}

type Query_GetIndexListServer interface {
	Send(*IndexID) error
	grpc.ServerStream
}

type queryGetIndexListServer struct {
	grpc.ServerStream
}

func (x *queryGetIndexListServer) Send(m *IndexID) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTimestamp(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVertex",
			Handler:    _Query_GetVertex_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _Query_GetEdge_Handler,
		},
		{
			MethodName: "GetTimestamp",
			Handler:    _Query_GetTimestamp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Traversal",
			Handler:       _Query_Traversal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Aggregate",
			Handler:       _Query_Aggregate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGraphs",
			Handler:       _Query_GetGraphs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetIndexList",
			Handler:       _Query_GetIndexList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aql.proto",
}

// Client API for Edit service

type EditClient interface {
	AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	StreamElements(ctx context.Context, opts ...grpc.CallOption) (Edit_StreamElementsClient, error)
	AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	AddSubGraph(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*EditResult, error)
	DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	AddIndex(ctx context.Context, in *IndexID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteIndex(ctx context.Context, in *IndexID, opts ...grpc.CallOption) (*EditResult, error)
}

type editClient struct {
	cc *grpc.ClientConn
}

func NewEditClient(cc *grpc.ClientConn) EditClient {
	return &editClient{cc}
}

func (c *editClient) AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) StreamElements(ctx context.Context, opts ...grpc.CallOption) (Edit_StreamElementsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Edit_serviceDesc.Streams[0], c.cc, "/aql.Edit/StreamElements", opts...)
	if err != nil {
		return nil, err
	}
	x := &editStreamElementsClient{stream}
	return x, nil
}

type Edit_StreamElementsClient interface {
	Send(*GraphElement) error
	CloseAndRecv() (*EditResult, error)
	grpc.ClientStream
}

type editStreamElementsClient struct {
	grpc.ClientStream
}

func (x *editStreamElementsClient) Send(m *GraphElement) error {
	return x.ClientStream.SendMsg(m)
}

func (x *editStreamElementsClient) CloseAndRecv() (*EditResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EditResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *editClient) AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddSubGraph(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddSubGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddIndex(ctx context.Context, in *IndexID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteIndex(ctx context.Context, in *IndexID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Edit service

type EditServer interface {
	AddVertex(context.Context, *GraphElement) (*EditResult, error)
	AddEdge(context.Context, *GraphElement) (*EditResult, error)
	StreamElements(Edit_StreamElementsServer) error
	AddGraph(context.Context, *ElementID) (*EditResult, error)
	AddSubGraph(context.Context, *Graph) (*EditResult, error)
	DeleteGraph(context.Context, *ElementID) (*EditResult, error)
	DeleteVertex(context.Context, *ElementID) (*EditResult, error)
	DeleteEdge(context.Context, *ElementID) (*EditResult, error)
	AddIndex(context.Context, *IndexID) (*EditResult, error)
	DeleteIndex(context.Context, *IndexID) (*EditResult, error)
}

func RegisterEditServer(s *grpc.Server, srv EditServer) {
	s.RegisterService(&_Edit_serviceDesc, srv)
}

func _Edit_AddVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddVertex(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddEdge(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_StreamElements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EditServer).StreamElements(&editStreamElementsServer{stream})
}

type Edit_StreamElementsServer interface {
	SendAndClose(*EditResult) error
	Recv() (*GraphElement, error)
	grpc.ServerStream
}

type editStreamElementsServer struct {
	grpc.ServerStream
}

func (x *editStreamElementsServer) SendAndClose(m *EditResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *editStreamElementsServer) Recv() (*GraphElement, error) {
	m := new(GraphElement)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Edit_AddGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddSubGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Graph)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddSubGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddSubGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddSubGraph(ctx, req.(*Graph))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddIndex(ctx, req.(*IndexID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteIndex(ctx, req.(*IndexID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Edit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Edit",
	HandlerType: (*EditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVertex",
			Handler:    _Edit_AddVertex_Handler,
		},
		{
			MethodName: "AddEdge",
			Handler:    _Edit_AddEdge_Handler,
		},
		{
			MethodName: "AddGraph",
			Handler:    _Edit_AddGraph_Handler,
		},
		{
			MethodName: "AddSubGraph",
			Handler:    _Edit_AddSubGraph_Handler,
		},
		{
			MethodName: "DeleteGraph",
			Handler:    _Edit_DeleteGraph_Handler,
		},
		{
			MethodName: "DeleteVertex",
			Handler:    _Edit_DeleteVertex_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _Edit_DeleteEdge_Handler,
		},
		{
			MethodName: "AddIndex",
			Handler:    _Edit_AddIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _Edit_DeleteIndex_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamElements",
			Handler:       _Edit_StreamElements_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "aql.proto",
}

func init() { proto.RegisterFile("aql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1865 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x4f, 0x73, 0xdb, 0xc6,
	0x15, 0x17, 0xf8, 0x1f, 0x8f, 0x94, 0x44, 0xad, 0x6c, 0x19, 0x66, 0xec, 0x4a, 0xb3, 0x71, 0x62,
	0x9a, 0xd5, 0x88, 0xb2, 0x1c, 0xa7, 0x89, 0x9a, 0x43, 0x25, 0x8b, 0x91, 0x39, 0xb5, 0xa9, 0x08,
	0x64, 0xec, 0xe6, 0x90, 0x78, 0x20, 0x62, 0x4d, 0x61, 0x0c, 0x02, 0x14, 0xb0, 0x94, 0xad, 0x7a,
	0xdc, 0xce, 0xf4, 0xde, 0x53, 0x3f, 0x52, 0x0f, 0x9d, 0x9e, 0x73, 0xe9, 0x07, 0xe8, 0x07, 0xc9,
	0xec, 0xdb, 0x05, 0x08, 0xfe, 0xb3, 0xe8, 0x13, 0xb9, 0xbb, 0xbf, 0xf7, 0x7b, 0xff, 0xdf, 0x2e,
	0x40, 0xb7, 0x2e, 0xdc, 0x9d, 0x41, 0xe0, 0x73, 0x9f, 0xa4, 0xad, 0x0b, 0xb7, 0x72, 0xa7, 0xe7,
	0xfb, 0x3d, 0x97, 0xd5, 0xad, 0x81, 0x53, 0xb7, 0x3c, 0xcf, 0xe7, 0x16, 0x77, 0x7c, 0x2f, 0x94,
	0x90, 0xf8, 0x14, 0x57, 0x67, 0xc3, 0xd7, 0xf5, 0x90, 0x07, 0xc3, 0x2e, 0x97, 0xa7, 0xf4, 0x39,
	0xc0, 0x71, 0x60, 0x0d, 0xce, 0x4f, 0x87, 0x2c, 0xb8, 0x22, 0x37, 0x20, 0xdb, 0x13, 0x2b, 0x43,
	0xdb, 0xd2, 0xaa, 0xba, 0x29, 0x17, 0xe4, 0x01, 0x64, 0x2f, 0xc4, 0xb1, 0x91, 0xda, 0x4a, 0x57,
	0x8b, 0x7b, 0xeb, 0x3b, 0x42, 0x3f, 0x4a, 0xb5, 0xb9, 0xc5, 0x59, 0x9f, 0x79, 0xdc, 0x94, 0x08,
	0xfa, 0x18, 0x0a, 0xc8, 0xd4, 0x66, 0x7c, 0x24, 0xa6, 0x5d, 0x2b, 0xf6, 0x0d, 0x2c, 0x3f, 0xb7,
	0x78, 0xf7, 0x3c, 0x96, 0xbd, 0x0f, 0x79, 0x71, 0xe2, 0xb0, 0x50, 0x49, 0x2f, 0xa3, 0x74, 0x74,
	0x6e, 0x46, 0xa7, 0xf4, 0xdf, 0x79, 0x58, 0x19, 0xe7, 0x24, 0x35, 0xd0, 0x2e, 0xd1, 0x81, 0xe2,
	0x5e, 0x65, 0x47, 0x3a, 0xbf, 0x13, 0x39, 0xbf, 0xf3, 0xcc, 0x09, 0xf9, 0x0b, 0xcb, 0x1d, 0xb2,
	0xa7, 0x4b, 0xa6, 0x76, 0x29, 0xb0, 0xcc, 0x48, 0x2d, 0x82, 0x65, 0x64, 0x1b, 0x52, 0x8e, 0x67,
	0xc0, 0x02, 0xe0, 0x94, 0xe3, 0x91, 0x1d, 0x48, 0xfb, 0x43, 0x6e, 0x14, 0x17, 0x80, 0x0b, 0x20,
	0x79, 0x0c, 0x79, 0xc7, 0x7b, 0xc5, 0xec, 0x1e, 0x33, 0x4a, 0x0b, 0xc8, 0xe4, 0x1c, 0xaf, 0x61,
	0xf7, 0x18, 0xf9, 0x03, 0x14, 0xfc, 0x21, 0x97, 0x72, 0xcb, 0x0b, 0xc8, 0xe5, 0xfd, 0x21, 0x47,
	0xc1, 0x5d, 0xc8, 0x9c, 0xf9, 0xfc, 0xdc, 0x58, 0x59, 0x40, 0x08, 0x91, 0xe4, 0x5b, 0xd0, 0xc5,
	0xaf, 0xd4, 0xb5, 0xba, 0x80, 0x58, 0x41, 0xc0, 0x51, 0x59, 0x19, 0x52, 0x56, 0x68, 0xdc, 0x10,
	0x45, 0x25, 0xc2, 0x63, 0x85, 0x64, 0x07, 0x72, 0x21, 0x73, 0x59, 0x97, 0x1b, 0x37, 0x91, 0xe9,
	0x06, 0xe6, 0xb7, 0x8d, 0x5b, 0x71, 0x2a, 0x85, 0x9f, 0x12, 0x45, 0x76, 0x21, 0x17, 0x30, 0xcf,
	0x66, 0x81, 0x71, 0x0b, 0xf1, 0x1b, 0x53, 0x9a, 0xe3, 0xc8, 0x48, 0x1c, 0xd9, 0x80, 0xac, 0xeb,
	0xf4, 0x1d, 0x6e, 0xdc, 0xde, 0xd2, 0xaa, 0xe9, 0xa7, 0x4b, 0xa6, 0x5c, 0x8a, 0xfd, 0xae, 0x3f,
	0xf4, 0xb8, 0x51, 0x51, 0xe6, 0xc8, 0x25, 0xf9, 0x06, 0x0a, 0xb6, 0x13, 0x72, 0xc7, 0xeb, 0x72,
	0x63, 0x73, 0x11, 0xef, 0x22, 0x34, 0xa9, 0x41, 0xb6, 0x2f, 0xaa, 0xd7, 0xa8, 0xa2, 0x18, 0x41,
	0x57, 0xc6, 0xea, 0x59, 0x68, 0x41, 0x08, 0x31, 0x20, 0xe7, 0xf4, 0x07, 0x7e, 0xc0, 0x8d, 0x3d,
	0xa5, 0x5e, 0xad, 0x09, 0x81, 0x74, 0xdf, 0x1a, 0x18, 0x8f, 0xd4, 0xb6, 0x58, 0x90, 0x2a, 0x64,
	0x5e, 0xfb, 0xae, 0x6d, 0x7c, 0x95, 0x20, 0xfe, 0xde, 0x77, 0xed, 0x64, 0x84, 0x10, 0x21, 0x78,
	0x5f, 0x3b, 0x2e, 0x67, 0x81, 0xf1, 0x75, 0xc4, 0x2b, 0xd7, 0x64, 0x1b, 0xb2, 0x6f, 0xcf, 0x59,
	0xc0, 0x8c, 0x6f, 0x13, 0x81, 0x7e, 0x29, 0x76, 0x1a, 0xef, 0x06, 0x01, 0x0b, 0x43, 0xc7, 0xf7,
	0x84, 0x7d, 0x08, 0x22, 0x5f, 0x09, 0x1e, 0xe6, 0xda, 0xa1, 0xb1, 0xbf, 0x48, 0x15, 0x4a, 0x2c,
	0x79, 0x08, 0xba, 0xd5, 0xeb, 0x05, 0xac, 0x67, 0x71, 0x66, 0xfc, 0x11, 0x05, 0xd7, 0x50, 0xcf,
	0x81, 0xda, 0x15, 0xf3, 0xe8, 0xe9, 0x92, 0x39, 0x42, 0x1d, 0x16, 0x41, 0x0f, 0x23, 0x2f, 0xe8,
	0x2b, 0x58, 0x4f, 0x22, 0x4d, 0x76, 0x31, 0x64, 0x21, 0x9f, 0x33, 0x8e, 0xf6, 0xa0, 0x64, 0x25,
	0xc0, 0x6a, 0x2a, 0xad, 0x8c, 0xe9, 0x63, 0xe6, 0x18, 0x86, 0x1e, 0x42, 0x29, 0xa9, 0x60, 0x8a,
	0x43, 0x5b, 0x80, 0xe3, 0x57, 0x0d, 0xf4, 0xf8, 0x8c, 0x10, 0xc8, 0x78, 0x56, 0x9f, 0x29, 0xd3,
	0xf0, 0x3f, 0xa9, 0x41, 0x86, 0xb3, 0xa0, 0xaf, 0x06, 0x8a, 0x8c, 0x74, 0x87, 0x05, 0xfd, 0x84,
	0x6a, 0x91, 0x30, 0x81, 0x21, 0xdf, 0x01, 0x0c, 0x58, 0xd0, 0x65, 0x1e, 0x77, 0x5c, 0x66, 0xa4,
	0x55, 0xb0, 0x85, 0xc4, 0x0f, 0xf1, 0xf6, 0xb8, 0x5c, 0x02, 0x2f, 0x7a, 0xf1, 0xdc, 0x09, 0xb9,
	0xdf, 0x0b, 0xac, 0xbe, 0x91, 0x41, 0xe1, 0xdb, 0x28, 0xfc, 0x34, 0xda, 0x1d, 0x97, 0x1d, 0xa1,
	0x0f, 0x97, 0xa1, 0x98, 0x70, 0x8b, 0x9e, 0xc2, 0xea, 0x84, 0x89, 0x22, 0xec, 0xae, 0x75, 0xc6,
	0xdc, 0x28, 0xec, 0xb8, 0x10, 0xbb, 0x98, 0x6d, 0xf4, 0x4e, 0x37, 0xe5, 0x42, 0x84, 0x21, 0x74,
	0xfe, 0x2a, 0x1d, 0xc8, 0x98, 0xf8, 0x9f, 0xbe, 0x82, 0x9b, 0x33, 0x7d, 0xf8, 0x24, 0xe2, 0x0a,
	0x14, 0x94, 0xbf, 0xa1, 0x91, 0xde, 0x4a, 0x57, 0x35, 0x33, 0x5e, 0xd3, 0x5f, 0xe0, 0xc6, 0x2c,
	0x3f, 0x3f, 0x95, 0xdf, 0xf1, 0x38, 0x0b, 0x2e, 0x2d, 0x57, 0x19, 0x1f, 0xaf, 0xe9, 0x2f, 0xb0,
	0xd1, 0xb2, 0xfa, 0xcc, 0x4e, 0x70, 0x9b, 0x2c, 0x1c, 0xba, 0x7c, 0x66, 0xd6, 0x77, 0x21, 0x7f,
	0x36, 0xec, 0xbe, 0x61, 0x3c, 0x2a, 0xc5, 0x8d, 0xc9, 0xd2, 0x97, 0xc2, 0x66, 0x04, 0xa3, 0x6d,
	0x58, 0x9b, 0xa6, 0xae, 0x42, 0xfa, 0x0d, 0xbb, 0x52, 0x17, 0xd7, 0x9c, 0xf1, 0x66, 0x0a, 0x88,
	0x70, 0xe8, 0x52, 0xac, 0xd0, 0x21, 0xcd, 0x94, 0x0b, 0xfa, 0x1c, 0xd6, 0x27, 0xba, 0x5a, 0x74,
	0x2a, 0xf9, 0x1a, 0x8a, 0x2c, 0xde, 0x89, 0x0a, 0x7d, 0xe6, 0x10, 0x30, 0x93, 0x40, 0xfa, 0x3f,
	0x0d, 0x56, 0x27, 0x00, 0x64, 0x1b, 0xd2, 0x96, 0x67, 0x2b, 0x13, 0x8d, 0x59, 0x1c, 0x42, 0xa5,
	0x18, 0x5e, 0x96, 0x67, 0x93, 0x1a, 0xa4, 0xfc, 0x40, 0xf5, 0xc2, 0xc7, 0xc0, 0x29, 0x3f, 0x10,
	0xce, 0x7b, 0x3e, 0x57, 0x6d, 0x30, 0x6f, 0x44, 0x09, 0x08, 0x79, 0x04, 0x7a, 0xd7, 0xf7, 0x6c,
	0x47, 0x44, 0x4e, 0x55, 0xfe, 0xfa, 0x08, 0xff, 0x24, 0x3a, 0x12, 0x35, 0x1f, 0xe3, 0x0e, 0x4b,
	0x00, 0x23, 0xdf, 0xe8, 0xdf, 0x60, 0x65, 0x1c, 0x4c, 0xca, 0xa3, 0xd8, 0xeb, 0x32, 0xc6, 0xdb,
	0xc9, 0x18, 0xcf, 0xcf, 0x87, 0x04, 0x91, 0xed, 0xa4, 0x51, 0xc2, 0x89, 0x15, 0x35, 0x4b, 0x62,
	0x15, 0x09, 0x6b, 0xe8, 0x03, 0x58, 0x9d, 0xb8, 0xe8, 0xc8, 0x06, 0xe4, 0xb0, 0x58, 0x65, 0x82,
	0x74, 0x53, 0xad, 0x68, 0x1b, 0x96, 0xc7, 0xe6, 0xbd, 0x00, 0x86, 0xfe, 0x30, 0xe8, 0x46, 0x25,
	0xa8, 0x56, 0x62, 0xf4, 0x38, 0x9e, 0xc3, 0xaf, 0x31, 0x17, 0x31, 0xf4, 0x67, 0xc8, 0xbd, 0x60,
	0x01, 0x67, 0xef, 0x84, 0xdf, 0x3d, 0xc7, 0x8e, 0xfc, 0xee, 0x39, 0xf6, 0xa8, 0x85, 0x52, 0xc9,
	0x16, 0xfa, 0x3d, 0x64, 0x6c, 0x8b, 0x5b, 0x2a, 0x3f, 0xb7, 0xa6, 0xd8, 0xdb, 0xf8, 0xa4, 0x34,
	0x11, 0x44, 0xff, 0x0e, 0x19, 0x75, 0xe9, 0x2f, 0x46, 0x4e, 0x20, 0xf3, 0x3a, 0xf0, 0xfb, 0x48,
	0xae, 0x9b, 0xf8, 0x9f, 0xac, 0x40, 0x8a, 0xfb, 0x98, 0x5e, 0xdd, 0x4c, 0x71, 0x3f, 0x36, 0x20,
	0xbb, 0x88, 0x01, 0xff, 0xd4, 0xa0, 0x88, 0x37, 0xaf, 0xea, 0xac, 0x2f, 0x20, 0x77, 0x89, 0xfe,
	0xaa, 0xca, 0x2d, 0x62, 0x6a, 0x64, 0x08, 0xc4, 0x25, 0x26, 0x0f, 0xc9, 0x26, 0x64, 0xf0, 0x69,
	0x23, 0x43, 0xa8, 0x23, 0x48, 0x38, 0x22, 0x46, 0xb6, 0x38, 0x20, 0xdb, 0xca, 0x88, 0xcc, 0x35,
	0x2f, 0x10, 0x44, 0x1d, 0x16, 0xc4, 0x8b, 0x45, 0xe8, 0xa7, 0x2f, 0x41, 0x57, 0x13, 0xc0, 0x7f,
	0x4b, 0xbe, 0x8c, 0x0a, 0x4b, 0xda, 0x52, 0x1e, 0xbd, 0x6b, 0x15, 0x46, 0x95, 0x14, 0x85, 0x74,
	0xe0, 0xbf, 0x55, 0x13, 0x65, 0x1a, 0x25, 0x0e, 0xe9, 0x9f, 0x00, 0x1a, 0xb6, 0xc3, 0x95, 0x9b,
	0x1b, 0x90, 0x65, 0x41, 0xe0, 0x07, 0x32, 0xe2, 0xe2, 0x4a, 0xc7, 0xa5, 0x78, 0x7c, 0x39, 0x6a,
	0xf8, 0xe1, 0xdb, 0xd4, 0x4e, 0x98, 0x76, 0x0e, 0x25, 0x7c, 0x3d, 0x37, 0x5c, 0x59, 0x5e, 0xb3,
	0x6f, 0xdc, 0xcf, 0xe3, 0x00, 0xa6, 0xa6, 0x02, 0x18, 0x87, 0xef, 0xae, 0x0a, 0x5f, 0x7a, 0x22,
	0x7c, 0x32, 0x78, 0xb4, 0x07, 0x59, 0xd4, 0x34, 0x47, 0xc5, 0x26, 0x64, 0x05, 0x2c, 0x1a, 0xa1,
	0x09, 0x71, 0xb9, 0x4f, 0xee, 0x43, 0x41, 0x28, 0x72, 0xba, 0x4c, 0xde, 0x07, 0x13, 0x56, 0xc4,
	0x87, 0x74, 0x13, 0xf2, 0xa8, 0xa8, 0x79, 0x34, 0x5b, 0x15, 0x7d, 0x08, 0xba, 0x72, 0x77, 0x1e,
	0x44, 0x94, 0x5f, 0x14, 0x32, 0x11, 0x30, 0x7a, 0x01, 0xf9, 0xa6, 0x67, 0xb3, 0x77, 0x73, 0x05,
	0x66, 0x57, 0x76, 0x7c, 0xf3, 0xa4, 0x93, 0x37, 0xcf, 0x3d, 0xc8, 0xf0, 0xab, 0x01, 0xc3, 0x32,
	0x5a, 0x51, 0xa9, 0x55, 0x06, 0x75, 0xae, 0x06, 0xcc, 0xc4, 0x53, 0xfa, 0x00, 0xf4, 0x8e, 0xd3,
	0x67, 0x21, 0xb7, 0xfa, 0x03, 0x72, 0x07, 0x74, 0x1e, 0x2d, 0x94, 0xe2, 0xd1, 0x06, 0xcd, 0x43,
	0xb6, 0xd1, 0x1f, 0xf0, 0xab, 0xda, 0x1b, 0xd0, 0x47, 0x33, 0xed, 0x26, 0xac, 0xfd, 0xd8, 0xfa,
	0x73, 0xeb, 0xe4, 0x65, 0xeb, 0xd5, 0x93, 0x93, 0xd6, 0x51, 0xb3, 0xd3, 0x3c, 0x69, 0x95, 0x97,
	0x48, 0x0e, 0x52, 0x8d, 0xd3, 0xb2, 0x46, 0xf2, 0x90, 0x6e, 0x35, 0x4e, 0xcb, 0x29, 0xb1, 0x71,
	0xdc, 0x29, 0xa7, 0xc5, 0xc6, 0x71, 0xa7, 0x51, 0xce, 0x88, 0x8d, 0x67, 0x9d, 0x72, 0x56, 0x6c,
	0x3c, 0xeb, 0x34, 0xca, 0x39, 0xb1, 0xd1, 0x6c, 0x95, 0xf3, 0xa4, 0x04, 0x85, 0x27, 0x27, 0xad,
	0xce, 0x41, 0xb3, 0xd5, 0x2e, 0x17, 0x6a, 0x8f, 0xa1, 0x98, 0xb0, 0x9a, 0x94, 0xa1, 0x14, 0xa9,
	0xeb, 0xfc, 0xf4, 0x43, 0xa3, 0xbc, 0x44, 0x00, 0x72, 0x2f, 0x1a, 0x66, 0xa7, 0xf1, 0x97, 0xb2,
	0x46, 0x0a, 0x90, 0x69, 0x1c, 0x1d, 0x37, 0xca, 0xa9, 0xbd, 0xff, 0x64, 0x20, 0x2b, 0x3f, 0x36,
	0x4d, 0xd0, 0x3b, 0x81, 0x75, 0xc9, 0x82, 0xd0, 0x72, 0xc9, 0xea, 0xe8, 0xeb, 0x10, 0x4f, 0x2b,
	0x72, 0x7e, 0xc6, 0x7d, 0x43, 0xe9, 0x3f, 0x7e, 0xfd, 0xff, 0xbf, 0x52, 0x77, 0xe8, 0xad, 0xfa,
	0xe5, 0xc3, 0x3a, 0x06, 0xbd, 0xfe, 0x1e, 0x7f, 0x3e, 0xd4, 0xf1, 0x1b, 0x72, 0x5f, 0xab, 0xed,
	0x6a, 0xc4, 0x4d, 0x3e, 0xd1, 0x8c, 0xa9, 0x27, 0xa8, 0x7a, 0x58, 0x56, 0x3e, 0xc3, 0x93, 0xd9,
	0x77, 0x3c, 0xfd, 0x12, 0x35, 0x6d, 0xd1, 0xcf, 0xa6, 0x35, 0xc5, 0xcf, 0x57, 0xa9, 0xed, 0x04,
	0xf4, 0x63, 0xc6, 0xd5, 0x2c, 0x5d, 0x49, 0x26, 0xb2, 0x79, 0x54, 0x49, 0x96, 0x27, 0xfd, 0x02,
	0x39, 0x37, 0xc9, 0xdd, 0x69, 0x4e, 0xd9, 0x3e, 0xf5, 0xf7, 0x8e, 0xfd, 0x81, 0x34, 0x21, 0x7f,
	0xcc, 0xe4, 0xf7, 0xd9, 0x24, 0xdd, 0xa8, 0x23, 0xe8, 0xe7, 0x48, 0x76, 0x97, 0xcc, 0x30, 0x50,
	0xf4, 0x8a, 0xa4, 0xfa, 0x0e, 0x6d, 0xc3, 0x80, 0x86, 0x04, 0xa4, 0xb0, 0x28, 0x92, 0xca, 0x04,
	0x31, 0x5d, 0x43, 0xb6, 0x22, 0xd1, 0x63, 0xb6, 0x5d, 0x8d, 0x3c, 0x87, 0xd2, 0x31, 0xe3, 0x58,
	0xf3, 0xf8, 0x8a, 0x28, 0x8d, 0xd2, 0xd3, 0x3c, 0xaa, 0xc8, 0x95, 0xea, 0x08, 0xba, 0x89, 0x04,
	0xb7, 0xc9, 0x8c, 0xcc, 0x38, 0x02, 0xb2, 0xab, 0x91, 0x36, 0xd2, 0x8d, 0xea, 0x79, 0xd2, 0x39,
	0xb9, 0x8e, 0xcf, 0x3f, 0xe6, 0x61, 0x5c, 0xf6, 0x7b, 0xff, 0xcd, 0x89, 0x8b, 0xc6, 0xe1, 0xe4,
	0x27, 0xd0, 0x0f, 0x6c, 0x5b, 0xa5, 0x61, 0x6d, 0x64, 0xa9, 0xe2, 0xaf, 0xac, 0xaa, 0xd0, 0x45,
	0x93, 0x92, 0x56, 0x91, 0x9e, 0x52, 0x63, 0x5e, 0x36, 0xf6, 0xa3, 0xa1, 0xd6, 0x86, 0xfc, 0x81,
	0x6d, 0x63, 0x42, 0x16, 0x21, 0xbe, 0x87, 0xc4, 0xbf, 0xa3, 0x1b, 0xb3, 0x33, 0xb3, 0x2f, 0xef,
	0x91, 0x26, 0xac, 0xb4, 0x79, 0xc0, 0xac, 0xbe, 0xe2, 0x09, 0x17, 0xe2, 0x56, 0x79, 0xa2, 0xa3,
	0x3c, 0x55, 0x35, 0xf2, 0x3d, 0x14, 0x0e, 0x6c, 0x5b, 0x0e, 0xd6, 0xc9, 0xa0, 0x4e, 0x31, 0xdc,
	0x46, 0x86, 0x75, 0xba, 0x36, 0x65, 0x1d, 0x39, 0x85, 0xe2, 0x81, 0x6d, 0xb7, 0x87, 0x67, 0x92,
	0x0a, 0x46, 0xf6, 0x4c, 0xd3, 0xa8, 0x5a, 0xa6, 0x95, 0x69, 0x27, 0xc3, 0xe1, 0x19, 0xfe, 0xdb,
	0xd7, 0x6a, 0xa4, 0x09, 0xc5, 0x23, 0xe6, 0x32, 0xce, 0x3e, 0xcd, 0xba, 0xda, 0x0c, 0xeb, 0x5e,
	0x40, 0x49, 0x52, 0xcd, 0x69, 0xb5, 0x79, 0x26, 0xd6, 0xae, 0x69, 0x37, 0x13, 0x40, 0xf2, 0xce,
	0xec, 0xb8, 0x29, 0x56, 0x55, 0x95, 0xb5, 0x8f, 0xf6, 0xdd, 0x8f, 0x98, 0x11, 0xec, 0x0d, 0x32,
	0xd6, 0x27, 0xd3, 0x7c, 0x35, 0xe4, 0xbb, 0x47, 0x37, 0xe7, 0x34, 0x4e, 0xfd, 0x3d, 0x5e, 0x23,
	0x1f, 0x44, 0x34, 0x7f, 0x8e, 0xa2, 0xb9, 0x10, 0x73, 0x1d, 0x99, 0x1f, 0xd4, 0xee, 0x5f, 0xc3,
	0x5c, 0x7f, 0x8f, 0x57, 0xd2, 0x87, 0xb3, 0x1c, 0x3e, 0x62, 0x1e, 0xfd, 0x16, 0x00, 0x00, 0xff,
	0xff, 0x21, 0xcb, 0x65, 0x86, 0x5b, 0x14, 0x00, 0x00,
}
