// Code generated by protoc-gen-go.
// source: aql.proto
// DO NOT EDIT!

/*
Package aql is a generated protocol buffer package.

It is generated from these files:
	aql.proto

It has these top-level messages:
	GraphQuery
	GraphStatement
	HasStatement
	SelectStatement
	Vertex
	Edge
	QueryResult
	ResultRow
	EditResult
	EdgeBundle
	GraphElement
	ElementID
	Empty
*/
package aql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GraphQuery struct {
	Graph string            `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Query []*GraphStatement `protobuf:"bytes,2,rep,name=query" json:"query,omitempty"`
}

func (m *GraphQuery) Reset()                    { *m = GraphQuery{} }
func (m *GraphQuery) String() string            { return proto.CompactTextString(m) }
func (*GraphQuery) ProtoMessage()               {}
func (*GraphQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GraphQuery) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphQuery) GetQuery() []*GraphStatement {
	if m != nil {
		return m.Query
	}
	return nil
}

type GraphStatement struct {
	// Types that are valid to be assigned to Statement:
	//	*GraphStatement_V
	//	*GraphStatement_E
	//	*GraphStatement_Label
	//	*GraphStatement_Has
	//	*GraphStatement_As
	//	*GraphStatement_In
	//	*GraphStatement_Out
	//	*GraphStatement_InEdge
	//	*GraphStatement_OutEdge
	//	*GraphStatement_InVertex
	//	*GraphStatement_OutVertex
	//	*GraphStatement_Select
	//	*GraphStatement_Values
	//	*GraphStatement_Limit
	//	*GraphStatement_Count
	//	*GraphStatement_GroupCount
	//	*GraphStatement_Import
	//	*GraphStatement_Map
	//	*GraphStatement_Fold
	Statement isGraphStatement_Statement `protobuf_oneof:"statement"`
}

func (m *GraphStatement) Reset()                    { *m = GraphStatement{} }
func (m *GraphStatement) String() string            { return proto.CompactTextString(m) }
func (*GraphStatement) ProtoMessage()               {}
func (*GraphStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isGraphStatement_Statement interface {
	isGraphStatement_Statement()
}

type GraphStatement_V struct {
	V string `protobuf:"bytes,1,opt,name=V,oneof"`
}
type GraphStatement_E struct {
	E string `protobuf:"bytes,2,opt,name=E,oneof"`
}
type GraphStatement_Label struct {
	Label string `protobuf:"bytes,3,opt,name=label,oneof"`
}
type GraphStatement_Has struct {
	Has *HasStatement `protobuf:"bytes,4,opt,name=has,oneof"`
}
type GraphStatement_As struct {
	As string `protobuf:"bytes,5,opt,name=as,oneof"`
}
type GraphStatement_In struct {
	In string `protobuf:"bytes,6,opt,name=in,oneof"`
}
type GraphStatement_Out struct {
	Out string `protobuf:"bytes,7,opt,name=out,oneof"`
}
type GraphStatement_InEdge struct {
	InEdge string `protobuf:"bytes,8,opt,name=inEdge,oneof"`
}
type GraphStatement_OutEdge struct {
	OutEdge string `protobuf:"bytes,9,opt,name=outEdge,oneof"`
}
type GraphStatement_InVertex struct {
	InVertex string `protobuf:"bytes,10,opt,name=inVertex,oneof"`
}
type GraphStatement_OutVertex struct {
	OutVertex string `protobuf:"bytes,11,opt,name=outVertex,oneof"`
}
type GraphStatement_Select struct {
	Select *SelectStatement `protobuf:"bytes,12,opt,name=select,oneof"`
}
type GraphStatement_Values struct {
	Values *SelectStatement `protobuf:"bytes,13,opt,name=values,oneof"`
}
type GraphStatement_Limit struct {
	Limit int64 `protobuf:"varint,14,opt,name=limit,oneof"`
}
type GraphStatement_Count struct {
	Count string `protobuf:"bytes,15,opt,name=count,oneof"`
}
type GraphStatement_GroupCount struct {
	GroupCount string `protobuf:"bytes,16,opt,name=groupCount,oneof"`
}
type GraphStatement_Import struct {
	Import string `protobuf:"bytes,50,opt,name=import,oneof"`
}
type GraphStatement_Map struct {
	Map string `protobuf:"bytes,51,opt,name=map,oneof"`
}
type GraphStatement_Fold struct {
	Fold string `protobuf:"bytes,52,opt,name=fold,oneof"`
}

func (*GraphStatement_V) isGraphStatement_Statement()          {}
func (*GraphStatement_E) isGraphStatement_Statement()          {}
func (*GraphStatement_Label) isGraphStatement_Statement()      {}
func (*GraphStatement_Has) isGraphStatement_Statement()        {}
func (*GraphStatement_As) isGraphStatement_Statement()         {}
func (*GraphStatement_In) isGraphStatement_Statement()         {}
func (*GraphStatement_Out) isGraphStatement_Statement()        {}
func (*GraphStatement_InEdge) isGraphStatement_Statement()     {}
func (*GraphStatement_OutEdge) isGraphStatement_Statement()    {}
func (*GraphStatement_InVertex) isGraphStatement_Statement()   {}
func (*GraphStatement_OutVertex) isGraphStatement_Statement()  {}
func (*GraphStatement_Select) isGraphStatement_Statement()     {}
func (*GraphStatement_Values) isGraphStatement_Statement()     {}
func (*GraphStatement_Limit) isGraphStatement_Statement()      {}
func (*GraphStatement_Count) isGraphStatement_Statement()      {}
func (*GraphStatement_GroupCount) isGraphStatement_Statement() {}
func (*GraphStatement_Import) isGraphStatement_Statement()     {}
func (*GraphStatement_Map) isGraphStatement_Statement()        {}
func (*GraphStatement_Fold) isGraphStatement_Statement()       {}

func (m *GraphStatement) GetStatement() isGraphStatement_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *GraphStatement) GetV() string {
	if x, ok := m.GetStatement().(*GraphStatement_V); ok {
		return x.V
	}
	return ""
}

func (m *GraphStatement) GetE() string {
	if x, ok := m.GetStatement().(*GraphStatement_E); ok {
		return x.E
	}
	return ""
}

func (m *GraphStatement) GetLabel() string {
	if x, ok := m.GetStatement().(*GraphStatement_Label); ok {
		return x.Label
	}
	return ""
}

func (m *GraphStatement) GetHas() *HasStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Has); ok {
		return x.Has
	}
	return nil
}

func (m *GraphStatement) GetAs() string {
	if x, ok := m.GetStatement().(*GraphStatement_As); ok {
		return x.As
	}
	return ""
}

func (m *GraphStatement) GetIn() string {
	if x, ok := m.GetStatement().(*GraphStatement_In); ok {
		return x.In
	}
	return ""
}

func (m *GraphStatement) GetOut() string {
	if x, ok := m.GetStatement().(*GraphStatement_Out); ok {
		return x.Out
	}
	return ""
}

func (m *GraphStatement) GetInEdge() string {
	if x, ok := m.GetStatement().(*GraphStatement_InEdge); ok {
		return x.InEdge
	}
	return ""
}

func (m *GraphStatement) GetOutEdge() string {
	if x, ok := m.GetStatement().(*GraphStatement_OutEdge); ok {
		return x.OutEdge
	}
	return ""
}

func (m *GraphStatement) GetInVertex() string {
	if x, ok := m.GetStatement().(*GraphStatement_InVertex); ok {
		return x.InVertex
	}
	return ""
}

func (m *GraphStatement) GetOutVertex() string {
	if x, ok := m.GetStatement().(*GraphStatement_OutVertex); ok {
		return x.OutVertex
	}
	return ""
}

func (m *GraphStatement) GetSelect() *SelectStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Select); ok {
		return x.Select
	}
	return nil
}

func (m *GraphStatement) GetValues() *SelectStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Values); ok {
		return x.Values
	}
	return nil
}

func (m *GraphStatement) GetLimit() int64 {
	if x, ok := m.GetStatement().(*GraphStatement_Limit); ok {
		return x.Limit
	}
	return 0
}

func (m *GraphStatement) GetCount() string {
	if x, ok := m.GetStatement().(*GraphStatement_Count); ok {
		return x.Count
	}
	return ""
}

func (m *GraphStatement) GetGroupCount() string {
	if x, ok := m.GetStatement().(*GraphStatement_GroupCount); ok {
		return x.GroupCount
	}
	return ""
}

func (m *GraphStatement) GetImport() string {
	if x, ok := m.GetStatement().(*GraphStatement_Import); ok {
		return x.Import
	}
	return ""
}

func (m *GraphStatement) GetMap() string {
	if x, ok := m.GetStatement().(*GraphStatement_Map); ok {
		return x.Map
	}
	return ""
}

func (m *GraphStatement) GetFold() string {
	if x, ok := m.GetStatement().(*GraphStatement_Fold); ok {
		return x.Fold
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GraphStatement) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GraphStatement_OneofMarshaler, _GraphStatement_OneofUnmarshaler, _GraphStatement_OneofSizer, []interface{}{
		(*GraphStatement_V)(nil),
		(*GraphStatement_E)(nil),
		(*GraphStatement_Label)(nil),
		(*GraphStatement_Has)(nil),
		(*GraphStatement_As)(nil),
		(*GraphStatement_In)(nil),
		(*GraphStatement_Out)(nil),
		(*GraphStatement_InEdge)(nil),
		(*GraphStatement_OutEdge)(nil),
		(*GraphStatement_InVertex)(nil),
		(*GraphStatement_OutVertex)(nil),
		(*GraphStatement_Select)(nil),
		(*GraphStatement_Values)(nil),
		(*GraphStatement_Limit)(nil),
		(*GraphStatement_Count)(nil),
		(*GraphStatement_GroupCount)(nil),
		(*GraphStatement_Import)(nil),
		(*GraphStatement_Map)(nil),
		(*GraphStatement_Fold)(nil),
	}
}

func _GraphStatement_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.V)
	case *GraphStatement_E:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.E)
	case *GraphStatement_Label:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Label)
	case *GraphStatement_Has:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Has); err != nil {
			return err
		}
	case *GraphStatement_As:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.As)
	case *GraphStatement_In:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.In)
	case *GraphStatement_Out:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Out)
	case *GraphStatement_InEdge:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.InEdge)
	case *GraphStatement_OutEdge:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OutEdge)
	case *GraphStatement_InVertex:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.InVertex)
	case *GraphStatement_OutVertex:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OutVertex)
	case *GraphStatement_Select:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Select); err != nil {
			return err
		}
	case *GraphStatement_Values:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Values); err != nil {
			return err
		}
	case *GraphStatement_Limit:
		b.EncodeVarint(14<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Count)
	case *GraphStatement_GroupCount:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.GroupCount)
	case *GraphStatement_Import:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Import)
	case *GraphStatement_Map:
		b.EncodeVarint(51<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Map)
	case *GraphStatement_Fold:
		b.EncodeVarint(52<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Fold)
	case nil:
	default:
		return fmt.Errorf("GraphStatement.Statement has unexpected type %T", x)
	}
	return nil
}

func _GraphStatement_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GraphStatement)
	switch tag {
	case 1: // statement.V
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_V{x}
		return true, err
	case 2: // statement.E
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_E{x}
		return true, err
	case 3: // statement.label
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Label{x}
		return true, err
	case 4: // statement.has
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Has{msg}
		return true, err
	case 5: // statement.as
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_As{x}
		return true, err
	case 6: // statement.in
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_In{x}
		return true, err
	case 7: // statement.out
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Out{x}
		return true, err
	case 8: // statement.inEdge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_InEdge{x}
		return true, err
	case 9: // statement.outEdge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_OutEdge{x}
		return true, err
	case 10: // statement.inVertex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_InVertex{x}
		return true, err
	case 11: // statement.outVertex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_OutVertex{x}
		return true, err
	case 12: // statement.select
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SelectStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Select{msg}
		return true, err
	case 13: // statement.values
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SelectStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Values{msg}
		return true, err
	case 14: // statement.limit
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Statement = &GraphStatement_Limit{int64(x)}
		return true, err
	case 15: // statement.count
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Count{x}
		return true, err
	case 16: // statement.groupCount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_GroupCount{x}
		return true, err
	case 50: // statement.import
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Import{x}
		return true, err
	case 51: // statement.map
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Map{x}
		return true, err
	case 52: // statement.fold
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Fold{x}
		return true, err
	default:
		return false, nil
	}
}

func _GraphStatement_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.V)))
		n += len(x.V)
	case *GraphStatement_E:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.E)))
		n += len(x.E)
	case *GraphStatement_Label:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Label)))
		n += len(x.Label)
	case *GraphStatement_Has:
		s := proto.Size(x.Has)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_As:
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.As)))
		n += len(x.As)
	case *GraphStatement_In:
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.In)))
		n += len(x.In)
	case *GraphStatement_Out:
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Out)))
		n += len(x.Out)
	case *GraphStatement_InEdge:
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.InEdge)))
		n += len(x.InEdge)
	case *GraphStatement_OutEdge:
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.OutEdge)))
		n += len(x.OutEdge)
	case *GraphStatement_InVertex:
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.InVertex)))
		n += len(x.InVertex)
	case *GraphStatement_OutVertex:
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.OutVertex)))
		n += len(x.OutVertex)
	case *GraphStatement_Select:
		s := proto.Size(x.Select)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Values:
		s := proto.Size(x.Values)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Limit:
		n += proto.SizeVarint(14<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Count)))
		n += len(x.Count)
	case *GraphStatement_GroupCount:
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.GroupCount)))
		n += len(x.GroupCount)
	case *GraphStatement_Import:
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Import)))
		n += len(x.Import)
	case *GraphStatement_Map:
		n += proto.SizeVarint(51<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Map)))
		n += len(x.Map)
	case *GraphStatement_Fold:
		n += proto.SizeVarint(52<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Fold)))
		n += len(x.Fold)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HasStatement struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Within []string `protobuf:"bytes,2,rep,name=within" json:"within,omitempty"`
}

func (m *HasStatement) Reset()                    { *m = HasStatement{} }
func (m *HasStatement) String() string            { return proto.CompactTextString(m) }
func (*HasStatement) ProtoMessage()               {}
func (*HasStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HasStatement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HasStatement) GetWithin() []string {
	if m != nil {
		return m.Within
	}
	return nil
}

type SelectStatement struct {
	Labels []string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
}

func (m *SelectStatement) Reset()                    { *m = SelectStatement{} }
func (m *SelectStatement) String() string            { return proto.CompactTextString(m) }
func (*SelectStatement) ProtoMessage()               {}
func (*SelectStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SelectStatement) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Vertex struct {
	Gid        string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label      string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Properties *google_protobuf1.Struct `protobuf:"bytes,3,opt,name=properties" json:"properties,omitempty"`
}

func (m *Vertex) Reset()                    { *m = Vertex{} }
func (m *Vertex) String() string            { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()               {}
func (*Vertex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Vertex) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Vertex) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Vertex) GetProperties() *google_protobuf1.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Edge struct {
	Gid        string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label      string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Src        string                   `protobuf:"bytes,3,opt,name=src" json:"src,omitempty"`
	Dst        string                   `protobuf:"bytes,4,opt,name=dst" json:"dst,omitempty"`
	Properties *google_protobuf1.Struct `protobuf:"bytes,5,opt,name=properties" json:"properties,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Edge) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Edge) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Edge) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Edge) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *Edge) GetProperties() *google_protobuf1.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

type QueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*QueryResult_Struct
	//	*QueryResult_Vertex
	//	*QueryResult_Edge
	//	*QueryResult_IntValue
	//	*QueryResult_FloatValue
	//	*QueryResult_StrValue
	Result isQueryResult_Result `protobuf_oneof:"result"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isQueryResult_Result interface {
	isQueryResult_Result()
}

type QueryResult_Struct struct {
	Struct *google_protobuf1.Struct `protobuf:"bytes,1,opt,name=struct,oneof"`
}
type QueryResult_Vertex struct {
	Vertex *Vertex `protobuf:"bytes,2,opt,name=vertex,oneof"`
}
type QueryResult_Edge struct {
	Edge *Edge `protobuf:"bytes,3,opt,name=edge,oneof"`
}
type QueryResult_IntValue struct {
	IntValue int32 `protobuf:"varint,4,opt,name=int_value,json=intValue,oneof"`
}
type QueryResult_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,5,opt,name=float_value,json=floatValue,oneof"`
}
type QueryResult_StrValue struct {
	StrValue string `protobuf:"bytes,6,opt,name=str_value,json=strValue,oneof"`
}

func (*QueryResult_Struct) isQueryResult_Result()     {}
func (*QueryResult_Vertex) isQueryResult_Result()     {}
func (*QueryResult_Edge) isQueryResult_Result()       {}
func (*QueryResult_IntValue) isQueryResult_Result()   {}
func (*QueryResult_FloatValue) isQueryResult_Result() {}
func (*QueryResult_StrValue) isQueryResult_Result()   {}

func (m *QueryResult) GetResult() isQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *QueryResult) GetStruct() *google_protobuf1.Struct {
	if x, ok := m.GetResult().(*QueryResult_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *QueryResult) GetVertex() *Vertex {
	if x, ok := m.GetResult().(*QueryResult_Vertex); ok {
		return x.Vertex
	}
	return nil
}

func (m *QueryResult) GetEdge() *Edge {
	if x, ok := m.GetResult().(*QueryResult_Edge); ok {
		return x.Edge
	}
	return nil
}

func (m *QueryResult) GetIntValue() int32 {
	if x, ok := m.GetResult().(*QueryResult_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *QueryResult) GetFloatValue() float64 {
	if x, ok := m.GetResult().(*QueryResult_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *QueryResult) GetStrValue() string {
	if x, ok := m.GetResult().(*QueryResult_StrValue); ok {
		return x.StrValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueryResult_OneofMarshaler, _QueryResult_OneofUnmarshaler, _QueryResult_OneofSizer, []interface{}{
		(*QueryResult_Struct)(nil),
		(*QueryResult_Vertex)(nil),
		(*QueryResult_Edge)(nil),
		(*QueryResult_IntValue)(nil),
		(*QueryResult_FloatValue)(nil),
		(*QueryResult_StrValue)(nil),
	}
}

func _QueryResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Struct:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Struct); err != nil {
			return err
		}
	case *QueryResult_Vertex:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vertex); err != nil {
			return err
		}
	case *QueryResult_Edge:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Edge); err != nil {
			return err
		}
	case *QueryResult_IntValue:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *QueryResult_FloatValue:
		b.EncodeVarint(5<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.FloatValue))
	case *QueryResult_StrValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StrValue)
	case nil:
	default:
		return fmt.Errorf("QueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _QueryResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueryResult)
	switch tag {
	case 1: // result.struct
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Struct)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Struct{msg}
		return true, err
	case 2: // result.vertex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Vertex)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Vertex{msg}
		return true, err
	case 3: // result.edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Edge)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Edge{msg}
		return true, err
	case 4: // result.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Result = &QueryResult_IntValue{int32(x)}
		return true, err
	case 5: // result.float_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Result = &QueryResult_FloatValue{math.Float64frombits(x)}
		return true, err
	case 6: // result.str_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &QueryResult_StrValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _QueryResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Struct:
		s := proto.Size(x.Struct)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Vertex:
		s := proto.Size(x.Vertex)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Edge:
		s := proto.Size(x.Edge)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_IntValue:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.IntValue))
	case *QueryResult_FloatValue:
		n += proto.SizeVarint(5<<3 | proto.WireFixed64)
		n += 8
	case *QueryResult_StrValue:
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StrValue)))
		n += len(x.StrValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResultRow struct {
	Value *QueryResult   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Row   []*QueryResult `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *ResultRow) Reset()                    { *m = ResultRow{} }
func (m *ResultRow) String() string            { return proto.CompactTextString(m) }
func (*ResultRow) ProtoMessage()               {}
func (*ResultRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResultRow) GetValue() *QueryResult {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResultRow) GetRow() []*QueryResult {
	if m != nil {
		return m.Row
	}
	return nil
}

type EditResult struct {
	// Types that are valid to be assigned to Result:
	//	*EditResult_Error
	//	*EditResult_Id
	Result isEditResult_Result `protobuf_oneof:"result"`
}

func (m *EditResult) Reset()                    { *m = EditResult{} }
func (m *EditResult) String() string            { return proto.CompactTextString(m) }
func (*EditResult) ProtoMessage()               {}
func (*EditResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isEditResult_Result interface {
	isEditResult_Result()
}

type EditResult_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,oneof"`
}
type EditResult_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,oneof"`
}

func (*EditResult_Error) isEditResult_Result() {}
func (*EditResult_Id) isEditResult_Result()    {}

func (m *EditResult) GetResult() isEditResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EditResult) GetError() string {
	if x, ok := m.GetResult().(*EditResult_Error); ok {
		return x.Error
	}
	return ""
}

func (m *EditResult) GetId() string {
	if x, ok := m.GetResult().(*EditResult_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EditResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EditResult_OneofMarshaler, _EditResult_OneofUnmarshaler, _EditResult_OneofSizer, []interface{}{
		(*EditResult_Error)(nil),
		(*EditResult_Id)(nil),
	}
}

func _EditResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case *EditResult_Id:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case nil:
	default:
		return fmt.Errorf("EditResult.Result has unexpected type %T", x)
	}
	return nil
}

func _EditResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EditResult)
	switch tag {
	case 1: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Error{x}
		return true, err
	case 2: // result.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Id{x}
		return true, err
	default:
		return false, nil
	}
}

func _EditResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case *EditResult_Id:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EdgeBundle struct {
	Src        string             `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Label      string             `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	FloatEdges map[string]float32 `protobuf:"bytes,3,rep,name=float_edges,json=floatEdges" json:"float_edges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	IntEdges   map[string]int64   `protobuf:"bytes,4,rep,name=int_edges,json=intEdges" json:"int_edges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StrEdges   map[string]string  `protobuf:"bytes,5,rep,name=str_edges,json=strEdges" json:"str_edges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *EdgeBundle) Reset()                    { *m = EdgeBundle{} }
func (m *EdgeBundle) String() string            { return proto.CompactTextString(m) }
func (*EdgeBundle) ProtoMessage()               {}
func (*EdgeBundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EdgeBundle) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *EdgeBundle) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *EdgeBundle) GetFloatEdges() map[string]float32 {
	if m != nil {
		return m.FloatEdges
	}
	return nil
}

func (m *EdgeBundle) GetIntEdges() map[string]int64 {
	if m != nil {
		return m.IntEdges
	}
	return nil
}

func (m *EdgeBundle) GetStrEdges() map[string]string {
	if m != nil {
		return m.StrEdges
	}
	return nil
}

type GraphElement struct {
	Graph      string      `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Vertex     *Vertex     `protobuf:"bytes,2,opt,name=vertex" json:"vertex,omitempty"`
	Edge       *Edge       `protobuf:"bytes,3,opt,name=edge" json:"edge,omitempty"`
	EdgeBundle *EdgeBundle `protobuf:"bytes,4,opt,name=edge_bundle,json=edgeBundle" json:"edge_bundle,omitempty"`
}

func (m *GraphElement) Reset()                    { *m = GraphElement{} }
func (m *GraphElement) String() string            { return proto.CompactTextString(m) }
func (*GraphElement) ProtoMessage()               {}
func (*GraphElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GraphElement) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphElement) GetVertex() *Vertex {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *GraphElement) GetEdge() *Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

func (m *GraphElement) GetEdgeBundle() *EdgeBundle {
	if m != nil {
		return m.EdgeBundle
	}
	return nil
}

type ElementID struct {
	Graph string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ElementID) Reset()                    { *m = ElementID{} }
func (m *ElementID) String() string            { return proto.CompactTextString(m) }
func (*ElementID) ProtoMessage()               {}
func (*ElementID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ElementID) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *ElementID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*GraphQuery)(nil), "aql.GraphQuery")
	proto.RegisterType((*GraphStatement)(nil), "aql.GraphStatement")
	proto.RegisterType((*HasStatement)(nil), "aql.HasStatement")
	proto.RegisterType((*SelectStatement)(nil), "aql.SelectStatement")
	proto.RegisterType((*Vertex)(nil), "aql.Vertex")
	proto.RegisterType((*Edge)(nil), "aql.Edge")
	proto.RegisterType((*QueryResult)(nil), "aql.QueryResult")
	proto.RegisterType((*ResultRow)(nil), "aql.ResultRow")
	proto.RegisterType((*EditResult)(nil), "aql.EditResult")
	proto.RegisterType((*EdgeBundle)(nil), "aql.EdgeBundle")
	proto.RegisterType((*GraphElement)(nil), "aql.GraphElement")
	proto.RegisterType((*ElementID)(nil), "aql.ElementID")
	proto.RegisterType((*Empty)(nil), "aql.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Query service

type QueryClient interface {
	Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error)
	GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error)
	GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error)
	GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[0], c.cc, "/aql.Query/Traversal", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryTraversalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_TraversalClient interface {
	Recv() (*ResultRow, error)
	grpc.ClientStream
}

type queryTraversalClient struct {
	grpc.ClientStream
}

func (x *queryTraversalClient) Recv() (*ResultRow, error) {
	m := new(ResultRow)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error) {
	out := new(Vertex)
	err := grpc.Invoke(ctx, "/aql.Query/GetVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error) {
	out := new(Edge)
	err := grpc.Invoke(ctx, "/aql.Query/GetEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[1], c.cc, "/aql.Query/GetGraphs", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryGetGraphsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_GetGraphsClient interface {
	Recv() (*ElementID, error)
	grpc.ClientStream
}

type queryGetGraphsClient struct {
	grpc.ClientStream
}

func (x *queryGetGraphsClient) Recv() (*ElementID, error) {
	m := new(ElementID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Query service

type QueryServer interface {
	Traversal(*GraphQuery, Query_TraversalServer) error
	GetVertex(context.Context, *ElementID) (*Vertex, error)
	GetEdge(context.Context, *ElementID) (*Edge, error)
	GetGraphs(*Empty, Query_GetGraphsServer) error
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Traversal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GraphQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).Traversal(m, &queryTraversalServer{stream})
}

type Query_TraversalServer interface {
	Send(*ResultRow) error
	grpc.ServerStream
}

type queryTraversalServer struct {
	grpc.ServerStream
}

func (x *queryTraversalServer) Send(m *ResultRow) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGraphs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).GetGraphs(m, &queryGetGraphsServer{stream})
}

type Query_GetGraphsServer interface {
	Send(*ElementID) error
	grpc.ServerStream
}

type queryGetGraphsServer struct {
	grpc.ServerStream
}

func (x *queryGetGraphsServer) Send(m *ElementID) error {
	return x.ServerStream.SendMsg(m)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVertex",
			Handler:    _Query_GetVertex_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _Query_GetEdge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Traversal",
			Handler:       _Query_Traversal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGraphs",
			Handler:       _Query_GetGraphs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aql.proto",
}

// Client API for Edit service

type EditClient interface {
	AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
}

type editClient struct {
	cc *grpc.ClientConn
}

func NewEditClient(cc *grpc.ClientConn) EditClient {
	return &editClient{cc}
}

func (c *editClient) AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Edit service

type EditServer interface {
	AddVertex(context.Context, *GraphElement) (*EditResult, error)
	AddEdge(context.Context, *GraphElement) (*EditResult, error)
	AddGraph(context.Context, *ElementID) (*EditResult, error)
	DeleteGraph(context.Context, *ElementID) (*EditResult, error)
	DeleteVertex(context.Context, *ElementID) (*EditResult, error)
	DeleteEdge(context.Context, *ElementID) (*EditResult, error)
}

func RegisterEditServer(s *grpc.Server, srv EditServer) {
	s.RegisterService(&_Edit_serviceDesc, srv)
}

func _Edit_AddVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddVertex(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddEdge(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Edit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Edit",
	HandlerType: (*EditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVertex",
			Handler:    _Edit_AddVertex_Handler,
		},
		{
			MethodName: "AddEdge",
			Handler:    _Edit_AddEdge_Handler,
		},
		{
			MethodName: "AddGraph",
			Handler:    _Edit_AddGraph_Handler,
		},
		{
			MethodName: "DeleteGraph",
			Handler:    _Edit_DeleteGraph_Handler,
		},
		{
			MethodName: "DeleteVertex",
			Handler:    _Edit_DeleteVertex_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _Edit_DeleteEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aql.proto",
}

func init() { proto.RegisterFile("aql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x4f, 0xe3, 0x46,
	0x14, 0x5f, 0xc7, 0x71, 0xc0, 0xcf, 0x2c, 0x84, 0x59, 0xc4, 0xba, 0xe9, 0x66, 0xa1, 0xb3, 0xa5,
	0x62, 0x39, 0x24, 0x90, 0xad, 0xd4, 0x15, 0x6d, 0xa5, 0x85, 0x6e, 0x16, 0x38, 0x54, 0x55, 0x4d,
	0x45, 0xd5, 0xd3, 0xca, 0xe0, 0x21, 0x58, 0x75, 0xec, 0x60, 0x8f, 0xa1, 0x68, 0xb5, 0x97, 0x5e,
	0x7b, 0xec, 0xad, 0x87, 0x5e, 0xfb, 0x09, 0xfa, 0x49, 0xfa, 0x15, 0xfa, 0x0d, 0xaa, 0xde, 0xab,
	0x79, 0x6f, 0xec, 0x84, 0x24, 0xfc, 0xe9, 0x29, 0x7e, 0xff, 0x7e, 0x79, 0xef, 0x37, 0xbf, 0x37,
	0x03, 0xb6, 0x7f, 0x1e, 0xb5, 0x06, 0x69, 0x22, 0x13, 0x66, 0xfa, 0xe7, 0x51, 0xe3, 0x49, 0x2f,
	0x49, 0x7a, 0x91, 0x68, 0xfb, 0x83, 0xb0, 0xed, 0xc7, 0x71, 0x22, 0x7d, 0x19, 0x26, 0x71, 0x46,
	0x29, 0x65, 0x14, 0xad, 0xe3, 0xfc, 0xb4, 0x9d, 0xc9, 0x34, 0x3f, 0x91, 0x14, 0xe5, 0x5f, 0x03,
	0xec, 0xa5, 0xfe, 0xe0, 0xec, 0xdb, 0x5c, 0xa4, 0x57, 0x6c, 0x09, 0xac, 0x9e, 0xb2, 0x5c, 0x63,
	0xd5, 0x58, 0xb7, 0x3d, 0x32, 0xd8, 0x73, 0xb0, 0xce, 0x55, 0xd8, 0xad, 0xac, 0x9a, 0xeb, 0x4e,
	0xe7, 0x51, 0x4b, 0xfd, 0x3f, 0x56, 0x1d, 0x4a, 0x5f, 0x8a, 0xbe, 0x88, 0xa5, 0x47, 0x19, 0xfc,
	0xf7, 0x2a, 0xcc, 0x5f, 0x8f, 0xb0, 0x79, 0x30, 0x8e, 0x08, 0x6f, 0xff, 0x81, 0x67, 0x1c, 0x29,
	0xbb, 0xeb, 0x56, 0x0a, 0xbb, 0xcb, 0x96, 0xc1, 0x8a, 0xfc, 0x63, 0x11, 0xb9, 0xa6, 0xf6, 0x91,
	0xc9, 0xd6, 0xc0, 0x3c, 0xf3, 0x33, 0xb7, 0xba, 0x6a, 0xac, 0x3b, 0x9d, 0x45, 0xfc, 0xcf, 0x7d,
	0x3f, 0x2b, 0x71, 0xf7, 0x1f, 0x78, 0x2a, 0xce, 0xea, 0x50, 0xf1, 0x33, 0xd7, 0xd2, 0xb5, 0x15,
	0xf2, 0x84, 0xb1, 0x5b, 0x2b, 0x3c, 0x61, 0xcc, 0x18, 0x98, 0x49, 0x2e, 0xdd, 0x19, 0xed, 0x52,
	0x06, 0x73, 0xa1, 0x16, 0xc6, 0xdd, 0xa0, 0x27, 0xdc, 0x59, 0xed, 0xd6, 0x36, 0x6b, 0xc0, 0x4c,
	0x92, 0x4b, 0x0c, 0xd9, 0x3a, 0x54, 0x38, 0xd8, 0x13, 0x98, 0x0d, 0xe3, 0x23, 0x91, 0x4a, 0xf1,
	0x93, 0x0b, 0x3a, 0x58, 0x7a, 0xd8, 0x53, 0xb0, 0x93, 0x5c, 0xea, 0xb0, 0xa3, 0xc3, 0x43, 0x17,
	0x6b, 0x41, 0x2d, 0x13, 0x91, 0x38, 0x91, 0xee, 0x1c, 0x4e, 0xb5, 0x84, 0x53, 0x1d, 0xa2, 0x6b,
	0x74, 0x30, 0x9d, 0xa5, 0xf2, 0x2f, 0xfc, 0x28, 0x17, 0x99, 0xfb, 0xf0, 0xf6, 0x7c, 0xca, 0x42,
	0x2a, 0xc3, 0x7e, 0x28, 0xdd, 0xf9, 0x55, 0x63, 0xdd, 0x44, 0x2a, 0x95, 0xa9, 0xfc, 0x27, 0x49,
	0x1e, 0x4b, 0x77, 0xa1, 0xa0, 0x18, 0x4d, 0xb6, 0x0a, 0xd0, 0x4b, 0x93, 0x7c, 0xf0, 0x15, 0x06,
	0xeb, 0x3a, 0x38, 0xe2, 0x43, 0x96, 0xfa, 0x83, 0x24, 0x95, 0x6e, 0xa7, 0x64, 0x09, 0x6d, 0xc5,
	0x69, 0xdf, 0x1f, 0xb8, 0x2f, 0x0a, 0x4e, 0xfb, 0xfe, 0x80, 0x2d, 0x41, 0xf5, 0x34, 0x89, 0x02,
	0xf7, 0x53, 0xed, 0x44, 0x6b, 0xd7, 0x01, 0x3b, 0x2b, 0x9a, 0xe5, 0x2f, 0x61, 0x6e, 0xf4, 0x14,
	0x59, 0x1d, 0xcc, 0x1f, 0xc5, 0x95, 0xd6, 0x9b, 0xfa, 0x64, 0xcb, 0x50, 0xbb, 0x0c, 0xe5, 0x59,
	0x18, 0xa3, 0xdc, 0x6c, 0x4f, 0x5b, 0xfc, 0x39, 0x2c, 0x8c, 0x4d, 0xae, 0x52, 0x51, 0x2b, 0x99,
	0x6b, 0x50, 0x2a, 0x59, 0x3c, 0x84, 0x9a, 0x66, 0xbc, 0x0e, 0x66, 0x2f, 0x0c, 0x0a, 0xf8, 0x5e,
	0x18, 0x28, 0x89, 0x93, 0xdc, 0x2a, 0x24, 0x71, 0x12, 0xdb, 0x67, 0x00, 0x83, 0x34, 0x19, 0x88,
	0x54, 0x86, 0x22, 0x43, 0x25, 0x3a, 0x9d, 0xc7, 0x2d, 0xda, 0x9c, 0x56, 0xb1, 0x39, 0xad, 0x43,
	0xdc, 0x1c, 0x6f, 0x24, 0x95, 0xff, 0x62, 0x40, 0x15, 0x95, 0x71, 0xdf, 0x7f, 0xaa, 0x83, 0x99,
	0xa5, 0x27, 0x24, 0x76, 0x4f, 0x7d, 0x2a, 0x4f, 0x90, 0x49, 0x14, 0xba, 0xed, 0xa9, 0xcf, 0xb1,
	0x6e, 0xac, 0xfb, 0x77, 0xf3, 0x8f, 0x01, 0x0e, 0x6e, 0xb2, 0x27, 0xb2, 0x3c, 0x92, 0x6c, 0x0b,
	0x6a, 0xb4, 0xed, 0xd8, 0xd7, 0xcd, 0x20, 0xa8, 0x39, 0xfc, 0x62, 0x6b, 0x50, 0xbb, 0x20, 0x01,
	0x57, 0xb0, 0xc4, 0x41, 0xcd, 0x11, 0x9d, 0x28, 0x35, 0x22, 0x76, 0x05, 0xaa, 0x42, 0x6d, 0x08,
	0x51, 0x65, 0x63, 0x92, 0xe2, 0x41, 0x9d, 0xba, 0x0a, 0xb0, 0x26, 0xd8, 0x61, 0x2c, 0xdf, 0xa2,
	0x32, 0x71, 0x36, 0x8b, 0x56, 0x45, 0x1e, 0x29, 0x0f, 0xfb, 0x08, 0x9c, 0xd3, 0x28, 0xf1, 0x8b,
	0x04, 0x35, 0xa3, 0xa1, 0xb4, 0x87, 0x4e, 0x4a, 0x69, 0x2a, 0xdd, 0xa4, 0x3a, 0xa1, 0x58, 0xe7,
	0xd9, 0x4c, 0xa6, 0x18, 0xde, 0x9d, 0x85, 0x5a, 0x8a, 0x53, 0xf2, 0xef, 0xc1, 0xa6, 0x79, 0xbd,
	0xe4, 0x92, 0x7d, 0x02, 0x16, 0x55, 0xd0, 0xc4, 0x75, 0xec, 0x6c, 0x84, 0x13, 0x8f, 0xc2, 0x8c,
	0x83, 0x99, 0x26, 0x97, 0xfa, 0x4a, 0x9b, 0xcc, 0x52, 0x41, 0xfe, 0x0a, 0xa0, 0x1b, 0x84, 0x52,
	0x93, 0xb9, 0x0c, 0x96, 0x48, 0xd3, 0x24, 0x2d, 0x2f, 0x33, 0x32, 0xf1, 0xbe, 0x09, 0xca, 0x1b,
	0xad, 0x12, 0x06, 0x23, 0xad, 0xfd, 0x61, 0x2a, 0x88, 0x9e, 0xd8, 0xcd, 0xe3, 0x20, 0x12, 0xc5,
	0xe1, 0x1b, 0xc3, 0xc3, 0x9f, 0x2e, 0x92, 0x57, 0x05, 0x3b, 0x8a, 0x4a, 0xa5, 0x47, 0xd5, 0xe4,
	0x4a, 0x49, 0x32, 0xa1, 0xb5, 0xde, 0xa8, 0x14, 0x65, 0x67, 0xdd, 0x58, 0xa6, 0x57, 0x9a, 0x3c,
	0x74, 0xb0, 0x6d, 0xa2, 0x9f, 0xea, 0xab, 0x58, 0xdf, 0x1c, 0xaf, 0x3f, 0x88, 0x47, 0xab, 0xd5,
	0xd9, 0x94, 0xb5, 0x8a, 0x78, 0xaa, 0xb5, 0xa6, 0xd7, 0x1e, 0xca, 0x74, 0xb4, 0x36, 0xd3, 0x66,
	0xe3, 0x4b, 0x58, 0x18, 0x6b, 0x6b, 0xca, 0x8a, 0x2f, 0x15, 0x67, 0xa4, 0x86, 0xae, 0xe8, 0x13,
	0xd9, 0xae, 0xbc, 0x34, 0x1a, 0x9f, 0xc3, 0xc3, 0x6b, 0x5d, 0xdd, 0x55, 0x6c, 0x8e, 0x15, 0x5f,
	0x6b, 0xeb, 0xae, 0x62, 0x7b, 0xa4, 0x98, 0xff, 0x66, 0xc0, 0x1c, 0xbe, 0x5c, 0xdd, 0x88, 0x2e,
	0x97, 0xe9, 0x6f, 0xe1, 0xb3, 0x5b, 0xd6, 0xa3, 0x5c, 0x8e, 0xe6, 0x0d, 0xcb, 0xa1, 0x57, 0x63,
	0x13, 0x1c, 0xf5, 0xfb, 0xf6, 0x18, 0xa9, 0xd4, 0x2f, 0xdc, 0xc2, 0x18, 0xc3, 0x1e, 0x88, 0xf2,
	0x9b, 0x6f, 0x81, 0xad, 0xdb, 0x3a, 0x78, 0x7d, 0x43, 0x63, 0xf3, 0x43, 0x15, 0x2a, 0x0d, 0xf2,
	0x19, 0xb0, 0xba, 0xfd, 0x81, 0xbc, 0xea, 0xfc, 0x59, 0x01, 0x8b, 0x5e, 0x77, 0x0f, 0xec, 0xef,
	0x52, 0xff, 0x42, 0xa4, 0x99, 0x1f, 0xb1, 0x85, 0xe1, 0x2b, 0x8e, 0xd1, 0xc6, 0x3c, 0x3a, 0xca,
	0x45, 0xe2, 0xfc, 0xe7, 0xbf, 0xfe, 0xfe, 0xb5, 0xf2, 0x84, 0x3f, 0x6e, 0x5f, 0x6c, 0xb5, 0xf1,
	0x3f, 0xda, 0xef, 0xf0, 0xe7, 0x7d, 0x1b, 0xdf, 0xfa, 0x6d, 0x63, 0x63, 0xd3, 0x60, 0xdf, 0x80,
	0xbd, 0x27, 0x8a, 0xf7, 0x8d, 0x20, 0xca, 0x4e, 0x1b, 0xa3, 0xe4, 0xf0, 0x35, 0xc4, 0x5b, 0x61,
	0xcd, 0x49, 0x3c, 0xa2, 0xad, 0xfd, 0x2e, 0x0c, 0xde, 0xb3, 0x03, 0x98, 0xd9, 0x13, 0xf4, 0xd8,
	0x8e, 0xc3, 0x0d, 0x89, 0xe4, 0xcf, 0x10, 0xac, 0xc9, 0x3e, 0x9c, 0x04, 0x53, 0xb4, 0x11, 0xd4,
	0x17, 0xd8, 0x1b, 0x8e, 0x98, 0x31, 0xa0, 0x62, 0x45, 0x49, 0x63, 0x0c, 0x98, 0x2f, 0x22, 0x9a,
	0xc3, 0xec, 0x12, 0x6d, 0xd3, 0xe8, 0xfc, 0x6b, 0xaa, 0x9b, 0x3d, 0x94, 0xec, 0x07, 0xb0, 0x77,
	0x82, 0x40, 0x8f, 0xb8, 0x38, 0xa4, 0x4d, 0xd7, 0x37, 0x8a, 0x93, 0x2b, 0x2e, 0x0a, 0xbe, 0x8e,
	0x70, 0x9c, 0xbb, 0x37, 0x4d, 0xba, 0x5d, 0x08, 0xe5, 0x10, 0x66, 0x76, 0x82, 0x00, 0x87, 0xbd,
	0x0f, 0xf0, 0xc7, 0x08, 0xfc, 0x94, 0x2f, 0x4f, 0x9f, 0x7a, 0x9b, 0xe4, 0xf5, 0x06, 0x66, 0x77,
	0x82, 0x60, 0x8f, 0x54, 0x31, 0x46, 0xe1, 0x04, 0xe4, 0x07, 0x08, 0xf9, 0x88, 0x2f, 0x4e, 0x40,
	0xb2, 0x03, 0x70, 0x5e, 0x8b, 0x48, 0x48, 0xf1, 0xff, 0xa0, 0x36, 0xa6, 0x40, 0x1d, 0xc1, 0x1c,
	0x41, 0xdd, 0x20, 0x94, 0x09, 0x2c, 0x2d, 0x96, 0x8d, 0x3b, 0xc4, 0xe2, 0x01, 0x10, 0xee, 0x54,
	0xbd, 0x4c, 0xa0, 0x6a, 0xd5, 0x6c, 0xdc, 0xa6, 0x9a, 0xe3, 0x1a, 0xbe, 0x8d, 0x2f, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0xf0, 0x27, 0x31, 0x66, 0x0b, 0x00, 0x00,
}
