# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multidriver.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='multidriver.proto',
  package='multidriver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11multidriver.proto\x12\x0bmultidriver\x1a\x1cgoogle/protobuf/struct.proto\"\x07\n\x05\x45mpty\"8\n\x03Row\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\'\n\x11\x43ollectionRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\",\n\nRowRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\x13\n\x05RowID\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bServiceInfo2\x95\x02\n\nCollection\x12J\n\x0eGetServiceInfo\x12\x1e.multidriver.CollectionRequest\x1a\x18.multidriver.ServiceInfo\x12>\n\x06GetIDs\x12\x1e.multidriver.CollectionRequest\x1a\x12.multidriver.RowID0\x01\x12=\n\x07GetRows\x12\x1e.multidriver.CollectionRequest\x1a\x10.multidriver.Row0\x01\x12<\n\x0bGetRowsByID\x12\x17.multidriver.RowRequest\x1a\x10.multidriver.Row(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='multidriver.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=71,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='multidriver.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='multidriver.Row.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='multidriver.Row.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=129,
)


_COLLECTIONREQUEST = _descriptor.Descriptor(
  name='CollectionRequest',
  full_name='multidriver.CollectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collection', full_name='multidriver.CollectionRequest.collection', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=170,
)


_ROWREQUEST = _descriptor.Descriptor(
  name='RowRequest',
  full_name='multidriver.RowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collection', full_name='multidriver.RowRequest.collection', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='multidriver.RowRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=216,
)


_ROWID = _descriptor.Descriptor(
  name='RowID',
  full_name='multidriver.RowID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='multidriver.RowID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=237,
)


_SERVICEINFO = _descriptor.Descriptor(
  name='ServiceInfo',
  full_name='multidriver.ServiceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=252,
)

_ROW.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['CollectionRequest'] = _COLLECTIONREQUEST
DESCRIPTOR.message_types_by_name['RowRequest'] = _ROWREQUEST
DESCRIPTOR.message_types_by_name['RowID'] = _ROWID
DESCRIPTOR.message_types_by_name['ServiceInfo'] = _SERVICEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.Empty)
  })
_sym_db.RegisterMessage(Empty)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.Row)
  })
_sym_db.RegisterMessage(Row)

CollectionRequest = _reflection.GeneratedProtocolMessageType('CollectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONREQUEST,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.CollectionRequest)
  })
_sym_db.RegisterMessage(CollectionRequest)

RowRequest = _reflection.GeneratedProtocolMessageType('RowRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROWREQUEST,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.RowRequest)
  })
_sym_db.RegisterMessage(RowRequest)

RowID = _reflection.GeneratedProtocolMessageType('RowID', (_message.Message,), {
  'DESCRIPTOR' : _ROWID,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.RowID)
  })
_sym_db.RegisterMessage(RowID)

ServiceInfo = _reflection.GeneratedProtocolMessageType('ServiceInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEINFO,
  '__module__' : 'multidriver_pb2'
  # @@protoc_insertion_point(class_scope:multidriver.ServiceInfo)
  })
_sym_db.RegisterMessage(ServiceInfo)



_COLLECTION = _descriptor.ServiceDescriptor(
  name='Collection',
  full_name='multidriver.Collection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=255,
  serialized_end=532,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetServiceInfo',
    full_name='multidriver.Collection.GetServiceInfo',
    index=0,
    containing_service=None,
    input_type=_COLLECTIONREQUEST,
    output_type=_SERVICEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetIDs',
    full_name='multidriver.Collection.GetIDs',
    index=1,
    containing_service=None,
    input_type=_COLLECTIONREQUEST,
    output_type=_ROWID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRows',
    full_name='multidriver.Collection.GetRows',
    index=2,
    containing_service=None,
    input_type=_COLLECTIONREQUEST,
    output_type=_ROW,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRowsByID',
    full_name='multidriver.Collection.GetRowsByID',
    index=3,
    containing_service=None,
    input_type=_ROWREQUEST,
    output_type=_ROW,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLLECTION)

DESCRIPTOR.services_by_name['Collection'] = _COLLECTION

# @@protoc_insertion_point(module_scope)
