# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digdriver.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='digdriver.proto',
  package='dig',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x64igdriver.proto\x12\x03\x64ig\x1a\x1cgoogle/protobuf/struct.proto\"\x07\n\x05\x45mpty\"\x1a\n\nCollection\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x13\n\x05RowID\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\nRowRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\trequestID\x18\x03 \x01(\x04\"K\n\x03Row\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x11\n\trequestID\x18\x03 \x01(\x04\"\x10\n\x0e\x43ollectionInfo2\xf6\x01\n\tDigSource\x12/\n\x0eGetCollections\x12\n.dig.Empty\x1a\x0f.dig.Collection0\x01\x12\x39\n\x11GetCollectionInfo\x12\x0f.dig.Collection\x1a\x13.dig.CollectionInfo\x12\'\n\x06GetIDs\x12\x0f.dig.Collection\x1a\n.dig.RowID0\x01\x12&\n\x07GetRows\x12\x0f.dig.Collection\x1a\x08.dig.Row0\x01\x12,\n\x0bGetRowsByID\x12\x0f.dig.RowRequest\x1a\x08.dig.Row(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='dig.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=61,
)


_COLLECTION = _descriptor.Descriptor(
  name='Collection',
  full_name='dig.Collection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dig.Collection.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=89,
)


_ROWID = _descriptor.Descriptor(
  name='RowID',
  full_name='dig.RowID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dig.RowID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=110,
)


_ROWREQUEST = _descriptor.Descriptor(
  name='RowRequest',
  full_name='dig.RowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collection', full_name='dig.RowRequest.collection', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='dig.RowRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestID', full_name='dig.RowRequest.requestID', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=175,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='dig.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dig.Row.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='dig.Row.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestID', full_name='dig.Row.requestID', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=252,
)


_COLLECTIONINFO = _descriptor.Descriptor(
  name='CollectionInfo',
  full_name='dig.CollectionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=270,
)

_ROW.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Collection'] = _COLLECTION
DESCRIPTOR.message_types_by_name['RowID'] = _ROWID
DESCRIPTOR.message_types_by_name['RowRequest'] = _ROWREQUEST
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['CollectionInfo'] = _COLLECTIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.Empty)
  })
_sym_db.RegisterMessage(Empty)

Collection = _reflection.GeneratedProtocolMessageType('Collection', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTION,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.Collection)
  })
_sym_db.RegisterMessage(Collection)

RowID = _reflection.GeneratedProtocolMessageType('RowID', (_message.Message,), {
  'DESCRIPTOR' : _ROWID,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.RowID)
  })
_sym_db.RegisterMessage(RowID)

RowRequest = _reflection.GeneratedProtocolMessageType('RowRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROWREQUEST,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.RowRequest)
  })
_sym_db.RegisterMessage(RowRequest)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.Row)
  })
_sym_db.RegisterMessage(Row)

CollectionInfo = _reflection.GeneratedProtocolMessageType('CollectionInfo', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONINFO,
  '__module__' : 'digdriver_pb2'
  # @@protoc_insertion_point(class_scope:dig.CollectionInfo)
  })
_sym_db.RegisterMessage(CollectionInfo)



_DIGSOURCE = _descriptor.ServiceDescriptor(
  name='DigSource',
  full_name='dig.DigSource',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=273,
  serialized_end=519,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCollections',
    full_name='dig.DigSource.GetCollections',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_COLLECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCollectionInfo',
    full_name='dig.DigSource.GetCollectionInfo',
    index=1,
    containing_service=None,
    input_type=_COLLECTION,
    output_type=_COLLECTIONINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetIDs',
    full_name='dig.DigSource.GetIDs',
    index=2,
    containing_service=None,
    input_type=_COLLECTION,
    output_type=_ROWID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRows',
    full_name='dig.DigSource.GetRows',
    index=3,
    containing_service=None,
    input_type=_COLLECTION,
    output_type=_ROW,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRowsByID',
    full_name='dig.DigSource.GetRowsByID',
    index=4,
    containing_service=None,
    input_type=_ROWREQUEST,
    output_type=_ROW,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGSOURCE)

DESCRIPTOR.services_by_name['DigSource'] = _DIGSOURCE

# @@protoc_insertion_point(module_scope)
