
Default: badger

Drivers:
  badger:
    Badger: grip-badger.db

  swapi-driver:
    Gripper:
      MappingFile: ./swapi.yaml
      Graph: swapi

Sources:
  tableServer: localhost:50051

Server:
  JobsDriver:
    File: jobs